### ISSUE TITLE
Kijiji app broken

### ISSUE THREAD

**Issue by weedy** [EnergizedProtection/block#1]
So I can see it wants Kijiji.demdex.net which is a CNAME of dcs-edge-va6-802167536.us-east-1.elb.amazonaws.com. Fine whitelist the domain. 
But the app is still broken. And as soon as I disable your list it works again but I don't see any other obvious domains (mostly Google APIs and eBay image servers).

Any idea what I'm missing?

**Comment by AdroitAdorKhan** [comment]
Hey! Thanks for letting us know!

We just had a look, and this _Kijiji_ App is full of trackers and analytics! Even that, _demdex_ one is an analytic too!

But no worry, will check the app and find a way to make it work again!
