### ISSUE TITLE
Unbound format issues

### ISSUE THREAD

**Issue by kravietz** [EnergizedProtection/block#116]
Hello, I tried to use the list in Unbound format but they fail due to syntax errors:

```
[1553892429] unbound-checkconf[20600:0] error: cannot parse name .xip.io
[1553892429] unbound-checkconf[20600:0] error: bad zone name .xip.io
redirect
local-zone: "api..coinmama.com" redirect
local-data: "api..coinmama.com A 0.0.0.0"
local-zone: "staging..coinmama.com" redirect
local-data: "staging..coinmama.com A 0.0.0.0"
```
Apparently, the domain names in Unbound cannot start with a dot `.` and cannot contain two dots `..`. After removing the offending domains Unbound was able to load it.

Also for faster loading and lower memory usage I would recommend that for Unbound the `static` domain type is used rather than `redirect`, so:
```
local-zone: "0-0-0-0-0-0proxy.tserv.se" static
```
Rather than the current:
```
local-zone: "0-0-0-0-0-0proxy.tserv.se" redirect
local-data: "0-0-0-0-0-0proxy.tserv.se A 0.0.0.0"
```
This change results in **huge** memory savings - instead of 6GB with the `redirect` format Unbound is down to 200MB.

**Comment by AdroitAdorKhan** [comment]
Maybe you can check now. Update done! 🤞

**Comment by xerta555** [comment]
@kravietz Be carreful if you have Magisk v19 installed on your device, it cause bootloop for stupid reasons for me and few other users.

If you don't have Magisk v19, avoid to install it and just run energized.

**Comment by AdroitAdorKhan** [comment]
> @kravietz Be carreful if you have Magisk v19 installed on your device, it cause bootloop for stupid reasons for me and few other users.
> 
> If you don't have Magisk v19, avoid to install it and just run energized.

No no! That's not related to magisk.

**Comment by xerta555** [comment]
> No no! That's not related to magisk.

I just said that bcz maybe that he use Magisk.

I know that his initial issue isn't related to Magisk but i just notify him about last Magisk beta version if he was going to update his setup..
