### ISSUE TITLE
https://www.miaminewtimes.com

### ISSUE THREAD

**Issue by terrorist96** [EnergizedProtection/block#12]
`https://www.miaminewtimes.com/news/turning-point-usa-fiu-chapter-shares-racist-sexist-pepe-memes-10827433` continue reading button doesn't work.

**Comment by AdroitAdorKhan** [comment]
Should get fixed on next release!

**Comment by terrorist96** [comment]
Not fixed.

**Comment by terrorist96** [comment]
@AdroitAdorKhan
