### ISSUE TITLE
Whitelist required for Moovit (transportation bus app)

### ISSUE THREAD

**Issue by Thomas499** [EnergizedProtection/block#122]
### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [X ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: 

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

``` Whitelist required
app4.moovitapp.com
  static.moovitapp.com
app4cdn.moovitapp.com
maps5.moovitapp.com


```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: 

- Version: 

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

![image](https://user-images.githubusercontent.com/38442058/55634596-ad307380-5773-11e9-9261-c848947bc30b.png)
![image](https://user-images.githubusercontent.com/38442058/55634573-a0ac1b00-5773-11e9-9a38-3d23ec2358fa.png)
**Whitelist the following to fix the issue:** 

<hr> Download Moovit app from google app store. Try to open it. Without whitlisting it will not open. Issue comes from the following two list 
https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/hosts.txt
https://github.com/jerryn70/GoodbyeAds

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

<p align="center"><a href="https://saythanks.io/to/AdroitAdorKhan" target="_blank"><img src="https://img.shields.io/badge/Say%20Thanks-!-1EAEDB.svg?longCache=true&style=flat-square"></a><p>

**Comment by jawz101** [comment]
fixing in the MobileAdsTrackers list. fyi @AdroitAdorKhan
