### ISSUE TITLE
Cnn

### ISSUE THREAD

**Issue by terrorist96** [EnergizedProtection/block#15]
`https://www-m.cnn.com/2018/10/22/politics/donald-trump-ted-cruz-rally-texas/index.html?r=https%3A%2F%2Fnews.google.com%2F`

Unblocked ad at beginning of video

**Comment by AdroitAdorKhan** [comment]
I am sorry! I couldn't reproduce your issue. Maybe a log or the ad source would really help.

**Comment by terrorist96** [comment]
I can't reproduce anymore either. I'll try to get a log next time.
