### ISSUE TITLE
Whitelist required to watch AcornTV app (british version of netflix)

### ISSUE THREAD

**Issue by Thomas499** [EnergizedProtection/block#151]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [X ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: 

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: **Hosts list that include api.rlje.net:**
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt
https://raw.githubusercontent.com/EnergizedProtection/block/master/basic/formats/hosts
https://raw.githubusercontent.com/EnergizedProtection/block/master/bluGo/formats/hosts
https://raw.githubusercontent.com/EnergizedProtection/block/master/blu/formats/hosts
https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/hosts.txt

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
api.rlje.net
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: 

- Version: 

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
**Whitelist Request:**
api.rlje.net

**Devices effected:**
All amazon firesticks

**Hosts list that include api.rlje.net:**
https://raw.githubusercontent.com/jerryn70/GoodbyeAds/master/Hosts/GoodbyeAds.txt
https://raw.githubusercontent.com/EnergizedProtection/block/master/basic/formats/hosts
https://raw.githubusercontent.com/EnergizedProtection/block/master/bluGo/formats/hosts
https://raw.githubusercontent.com/EnergizedProtection/block/master/blu/formats/hosts
https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/hosts.txt

**Effects of having list above enabled without api.rlje.net on whitelist:**
When user tries to use AcornTV app, which is a paid subscription service popular in Britain that allows the user to watch certain movies and tv shows (Very similar to Netflix), this is what comes up. There is only a blank black screen where the movies and shows should be listed. 
![image](https://user-images.githubusercontent.com/38442058/56513980-e47b8000-64e8-11e9-97c7-7457f32b36b0.png)

**Effects of whitelisting:**
![image](https://user-images.githubusercontent.com/38442058/56514007-f9581380-64e8-11e9-92ff-c28ef545de0c.png)

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

<p align="center"><a href="https://saythanks.io/to/AdroitAdorKhan" target="_blank"><img src="https://img.shields.io/badge/Say%20Thanks-!-1EAEDB.svg?longCache=true&style=flat-square"></a><p>

**Comment by jawz101** [comment]
fixing upstream
https://github.com/jawz101/MobileAdTrackers

**Comment by Thomas499** [comment]
So Jawz101/MobileAdTrackers is where we need to start reporting issues to so that the changes effect all of the energized list?

**Comment by jawz101** [comment]
no.  I just did an update a few weeks ago that pulled in a bit of false positives.  Since Energized uses mine as one of its base lists and has a larger userbase I've been watching his issues to remove any that were reported.

I've also been cleaning it up on my own quite a bit but he hasn't done a list update of his sources in the past few weeks.

**Comment by AvinashReddy3108** [comment]
@jawz101 @jawz101 Thanks for cleaning your list and letting us use it too !!

**Comment by jawz101** [comment]
It's a fun hobby.  I want it to just be limited to mobile ads & tracking networks and let other lists handle browser ads.  I just had this idea to take the OpenDNS 1 million most queried domains and whittle it down from there, and then add that to the blocklist.  I looked for ones that had certain strings in the domain name, didn't fall in some categorical lists that some site filtering progs use (ex: education, govt, web hosting, etc.), weren't common servers (dns, ntp, smtp, etc.), weren't randomly generated subdomains (googlevideo/netflix/etc.) and got it down to about 29,800.  At some point I just couldn't sit on it any more without others using it.

I was a little shocked that some businesses were using Energized (I just suggest sticking with StevenBlack's) but mine is getting normal again and is a great addition for both iOS and Android devices.
