### ISSUE TITLE
ampersand in hostname

### ISSUE THREAD

**Issue by Mausy5043** [EnergizedProtection/block#16]
ultimate\formats\hosts.txt contains:
`&quotc.smartclick.net`

Notably the ampersand at the start is what my code has stumbled upon/over.

**Comment by k4rn8g3** [comment]
@Mausy5043 May I know what code are you talking about ??

And yes the & should not be there (afaik). We will have a look at it..

**Comment by Mausy5043** [comment]
I'm developing [`uss_cygnus`](https://gitlab.com/mausy5043/uss_cygnus). It uses your ultimate list (amongst others) and while validating the test results I came across this one.

Glad to be of assistance.
