### ISSUE TITLE
Myjio and jiocinema apps have issues.

### ISSUE THREAD

**Issue by nihalanand697** [EnergizedProtection/block#168]
Myjio and jiocinema apps are unable to connect to the internet if energized protection is on.

**Comment by AvinashReddy3108** [comment]
#whitelist http://rtss-prod.jioconnect.com for MyJio app to work properly.

**Comment by nihalanand697** [comment]
Thanks for replying, I added this domain yo white list but no success. :(

**Comment by AdroitAdorKhan** [comment]
This should have been fixed with the latest update as per user feedback. Kindly update to the latest release, and re-open the issue if it's not working for you.

**Comment by nihalanand697** [comment]
Thank you guys so much, yes it is fixed for both the apps now. ❤

Mon Jun 03 10:21:56 GMT+05:30 2019 Ador <notifications@github.com>:
