### ISSUE TITLE
Errors.

### ISSUE THREAD

**Issue by shikulja** [EnergizedProtection/block#172]
ABP Opera addon - not working filters
only uBlock help he run

hostsMan - this source is not compatible
http://skrinshoter.ru/s/050619/tLG1vHaW?a

not work  comments on
https://3dnews.ru/
https://3dnews.ru/988455
Energized Ultimate Protection

keweonDNS changed in the settings of the router, and even in the system using DnsJumper
but the DNS security check failed on the site, although I’m sure that the DNS has changed

**Comment by AdroitAdorKhan** [comment]
Can you help with the log for those broken comments?

**Comment by DandelionSprout** [comment]
I can confirm that neither ABP or Opera can use the lists at the time of writing due to the absence of `[Adblock Plus n.n]` headers. This is currently being worked on at last.
