### ISSUE TITLE
yadi.sk

### ISSUE THREAD

**Issue by shikulja** [EnergizedProtection/block#173]
OPERA uBlock

https://yadi.sk/d/yW8xa5NJgUo5z

Energized Ultimate Protection

folder navigation does not work (empty list)

**Comment by AdroitAdorKhan** [comment]
It's working for me. Maybe you can check if anything else is causing this issue for you!

**Comment by RYU81** [comment]
doesn't work for me.

**Comment by AdroitAdorKhan** [comment]
Then grab a log, and check what's blocked!

**Comment by shikulja** [comment]
I tried, after the update, everything works
19.06.154

**Comment by AdroitAdorKhan** [comment]
Then it's fixed!
