### ISSUE TITLE
kob.com

### ISSUE THREAD

**Issue by terrorist96** [EnergizedProtection/block#177]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: blu

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```

```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: 

- Version: 

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
Unblocked video ad.
`https://www.kob.com/albuquerque-news/police-investigating-rainbow-crosswalk-vandalism-as-possible-hate-crime/5380398/`

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

<p align="center"><a href="https://saythanks.io/to/AdroitAdorKhan" target="_blank"><img src="https://img.shields.io/badge/Say%20Thanks-!-1EAEDB.svg?longCache=true&style=flat-square"></a><p>

**Comment by AdroitAdorKhan** [comment]
Can you help me with the video source? No video ad is popping up for me!

**Comment by terrorist96** [comment]
From ublock origin:

<details><summary>Logger output</summary>

| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +13 | \|\|fwmrm.net^ | -- | `www.kob.com` | 3 | image | `http://7cfe7.v.fwmrm.net/ad/l/1?s=c121&n=511975%3B511975&t=1560472391269321024&f=&r=511975&adid=32955786&reid=16655512&arid=0&auid=&cn=_pause&et=s&_cc=&tpos=0` |
| +12 |  |  | `www.kob.com` | 3 | xhr | `https://snqusdnbgfofq3fjdco7hofysc.gcdn.anvato.net/ua_hubbard_kob/480/19/06/06/4673201/5A693A1EE16DFF284437D33D3C9DA0E5835A2D8116BCF96C-6.ts?Expires=1560493998&KeyName=mcpkey1&Signature=TkJevh6SG-HlaoiqR79TxvTE_UE` |
| +12 |  |  | `www.kob.com` | 3 | xhr | `https://snqusdnbgfofq3fjdco7hofysc.gcdn.anvato.net/ua_hubbard_kob/480/19/06/06/4673201/5A693A1EE16DFF284437D33D3C9DA0E5835A2D8116BCF96C-5.ts?Expires=1560493998&KeyName=mcpkey1&Signature=8_41yGS2_FEGJ8gj_RmUYK_NRoI` |
| +11 |  |  | `www.kob.com` | 3 | xhr | `https://snqusdnbgfofq3fjdco7hofysc.gcdn.anvato.net/ua_hubbard_kob/480/19/06/06/4673201/5A693A1EE16DFF284437D33D3C9DA0E5835A2D8116BCF96C-4.ts?Expires=1560493998&KeyName=mcpkey1&Signature=QCL4pCejxaQADoFSZ1O2Sfgpu74` |
| +11 |  |  | `www.kob.com` | 3 | xhr | `https://snqusdnbgfofq3fjdco7hofysc.gcdn.anvato.net/ua_hubbard_kob/480/19/06/06/4673201/5A693A1EE16DFF284437D33D3C9DA0E5835A2D8116BCF96C-3.ts?Expires=1560493998&KeyName=mcpkey1&Signature=_kYPBVLGHUSrHkeIefJRN8123Uo` |
| +11 |  |  | `www.kob.com` | 3 | image | `https://nirx74twfblvgbzze3cy4q5pja.gcdn.anvato.net/captures/B70/09E/B7009E54C3A54C51828C3E166C3FEEA9_160x90.jpg?Expires=1560475991&KeyName=mcpkey1&Signature=5P8Xk6EZI6EAJRv7bDxw6MSybgI` |
| +10 |  |  | `www.kob.com` | 3 | xhr | `https://snqusdnbgfofq3fjdco7hofysc.gcdn.anvato.net/ua_hubbard_kob/480/19/06/06/4673201/5A693A1EE16DFF284437D33D3C9DA0E5835A2D8116BCF96C-2.ts?Expires=1560493998&KeyName=mcpkey1&Signature=WwqoKed98fkrhwym8zwSjzIePM8` |
| +10 |  |  | `www.kob.com` | 3 | xhr | `https://snqusdnbgfofq3fjdco7hofysc.gcdn.anvato.net/ua_hubbard_kob/480/19/06/06/4673201/5A693A1EE16DFF284437D33D3C9DA0E5835A2D8116BCF96C-1.ts?Expires=1560493998&KeyName=mcpkey1&Signature=PFASwG-ordxJcbztAZvQ0mp1qVY` |
| +10 |  |  | `www.kob.com` | 3 | xhr | `https://dcs-vod.apis.anvato.net/vod/p/1359200/prog.m3u8?i=i177602643-n30ec8e0a-6cf9-43af-8e6d-0835f889e5ef&anvtrid=157dba69077122cf7996ae732636ed99` |
| +9 |  |  | `www.kob.com` | 3 | xhr | `https://dcs-jite-df9y0sk8rfj8p7d7.gcdn.anvato.net/prod/9945E02ACEB24662B4DFB71DF6950DB7/350000/segment-2.ts` |
| +9 | \|\|fwmrm.net^ | -- | `www.kob.com` | 3 | image | `http://7cfe7.v.fwmrm.net/ad/l/1?s=c121&n=511975%3B511975&t=1560472391269321024&f=&r=511975&adid=32955786&reid=16655512&arid=0&auid=&cn=defaultImpression&et=i&_cc=32955786,16655512,,,1560472391,1&tpos=0&iw=&uxnw=&uxss=&uxct=&metr=47&init=1&asid=214617107&ssid=8329695&vcid2=511975%3A3039eaa3d51380e092a4ba0610191a4e3007&cr=` |
| +9 |  |  | `www.kob.com` | 3 | image | `https://dcs-png.apis.anvato.net/a?q=9OFYxYfS2Y1ZL3gnT5zI6vzq6PFp65Rcz5sc6WgQTSTSyDqq6YESB3scTSfQ6Oo5T4zryOccT4UStcZc.OFsxlNszYGc6qbNUSbpLqEz.EcrNg8r.5cr3XsUN4U33F.uUvcR3WdKyDVPTSc1t3TgfVu4t39Ey31r63ent39ETOzn65eI6DNmz2RqJ4ec6qgIt39EzDV5f3H` |
| +9 | \|\|fwmrm.net^ | -- | `www.kob.com` | 3 | image | `http://7cfe7.v.fwmrm.net/ad/l/1?s=c121&n=511975%3B511975&t=1560472391269321024&f=&cn=slotImpression&et=i&tpos=0&init=1&slid=0,1` |
| +9 |  |  | `www.kob.com` | 3 | xhr | `https://dcs-jite-df9y0sk8rfj8p7d7.gcdn.anvato.net/prod/9945E02ACEB24662B4DFB71DF6950DB7/350000/segment-1.ts` |
| +9 |  |  | `www.kob.com` | 3 | xhr | `https://dcs-vod.apis.anvato.net/vod/p/729200/prog.m3u8?i=i177602643-n30ec8e0a-6cf9-43af-8e6d-0835f889e5ef&anvtrid=157dba69077122cf7996ae732636ed99` |
| +9 |  |  | `www.kob.com` | 3 | xhr | `https://dcs-vod.apis.anvato.net/vod/p/session/master.m3u8?i=i177602643-n30ec8e0a-6cf9-43af-8e6d-0835f889e5ef&anvtrid=157dba69077122cf7996ae732636ed99` |
| +5 |  |  | `www.kob.com` | 3 | image | `https://sxctfxrky6wda5nttdwgjpgrde.gcdn.anvato.net/anv-pvw/80F/645/80F64590939E4C8BA8344FC85529F0AE_pvw-med.bif?Expires=1560475991&KeyName=mcpkey1&Signature=CDp21qqx-KPM3GJHZBO8KQYb8og` |
| +5 |  |  | `www.kob.com` | 3 | image | `https://sxctfxrky6wda5nttdwgjpgrde.gcdn.anvato.net/anv-pvw/80F/645/80F64590939E4C8BA8344FC85529F0AE_pvw-lo.bif?Expires=1560475991&KeyName=mcpkey1&Signature=KMlH816i5yXAJV3xVft_IcOORyo` |
| +5 |  |  | `www.kob.com` | 3 | image | `https://sxctfxrky6wda5nttdwgjpgrde.gcdn.anvato.net/anv-pvw/80F/645/80F64590939E4C8BA8344FC85529F0AE_pvw-hi.bif?Expires=1560475991&KeyName=mcpkey1&Signature=RtBW1gpBeKbnhr27lnSOKWBMfBs` |
| +5 |  |  | `www.kob.com` | 3 | image | `https://sxctfxrky6wda5nttdwgjpgrde.gcdn.anvato.net/anv-pvw/80F/645/80F64590939E4C8BA8344FC85529F0AE_pvw-M00.jpg?Expires=1560475991&KeyName=mcpkey1&Signature=eHaNMSNkSOmlWJ3Kv2fL0TDuXt8` |
| +5 |  |  | `www.kob.com` | 3 | image | `https://sxctfxrky6wda5nttdwgjpgrde.gcdn.anvato.net/anv-pvw/80F/645/80F64590939E4C8BA8344FC85529F0AE_pvw-M3.jpg?Expires=1560475991&KeyName=mcpkey1&Signature=4GgDJFhIJcFNAH-n58bVrmgX-Uc` |
| +5 |  |  | `www.kob.com` | 3 | image | `https://sxctfxrky6wda5nttdwgjpgrde.gcdn.anvato.net/anv-pvw/80F/645/80F64590939E4C8BA8344FC85529F0AE_pvw-M2.jpg?Expires=1560475991&KeyName=mcpkey1&Signature=chQmdg8VLDW-63ldl6KE5nTPx9Y` |
| +5 |  |  | `www.kob.com` | 3 | image | `https://sxctfxrky6wda5nttdwgjpgrde.gcdn.anvato.net/anv-pvw/80F/645/80F64590939E4C8BA8344FC85529F0AE_pvw-M1.jpg?Expires=1560475991&KeyName=mcpkey1&Signature=67-FNIEgkpNEUbSBNPgo2FzJPm4` |
| +5 |  |  | `www.kob.com` | 3 | image | `https://sxctfxrky6wda5nttdwgjpgrde.gcdn.anvato.net/anv-pvw/80F/645/80F64590939E4C8BA8344FC85529F0AE_pvw-M0.jpg?Expires=1560475991&KeyName=mcpkey1&Signature=m9TJG0d75rnpJyR1jNGety76OWc` |
| +3 |  |  | `www.kob.com` | 3 | image | `https://nirx74twfblvgbzze3cy4q5pja.gcdn.anvato.net/captures/B70/09E/B7009E54C3A54C51828C3E166C3FEEA9.jpg?Expires=1560475991&KeyName=mcpkey1&Signature=XqSnRyPSSEJnAUniWBASXBOC2cM` |
| +3 | \|\|google-analytics.com^ | -- | `www.kob.com` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +3 |  |  | `www.kob.com` | 3 | frame | `https://www.facebook.com/tr/` |
| +3 |  |  | `www.kob.com` | 3 | xhr | `https://dcs-vod.apis.anvato.net/vod/TkieXooiuU6NblP_jdGIlgr6KqiAYwX34lU7paBijjQPJzoYkiQHwFotOeLWdRAYL1sPfCta-NgNTT01VHQnP94cYTPKMds4cAtgfsWtHFSMWZT_J_I6QZnQJ3NqubZd/NizrkPi0BezmnWkWpju7iEEXVLp1QQJnLEnmacBmhhV4At_yx3s1tng0AWlDhB3GQCe8lmPJ2iGFKM7yneR4m8eVMN-l80uD0huEc5w59gO8_YdIA__JWcdfPNRxHK-M/H1OvgtE5bcTSpBdIxK4q1PlWhJ8c0p7HPoW4VLvTvxEDzQC6z7yw0yVTVuw__OPnqjQzz-GOIp_l-Du0YilG78DbsstK-byCPO6awGGrR-PwQ85ov0oj8XtKa6X3omym/9-uLP8FQ8JgbwmRhIyw0MKI0rRAKsjJ4iyY0Oq5RXNHZZN7NezDFMEWfQ4IRlyCoBtkM78wDF3c6GEWiZFUfrf__E3zxAxDNYqs5NwnWC0rthj_IPzHsgu6sVwaJR2jq/t1TINQqY7hbu2gr-DhMJtO3WBSDvlDICYgo_g7BAb4IY4knarRXvhZhsP6bX2ZUeS9yz1l_Qh5-l5YbCkpe-FKBHL64A36riQyJ261Rv9qmVEk55enTD8N3ZbSRWBMfX/5x22zmf2ytjbgTmrJBSzfOqYw6awaD8088q38AuYpWQplMwd96IjvXsiy8Vz8Kzp1m_y0F0MksGumErpZQDAy8YwUdMjdDB2DAKh6WhPO7yQvTDU_txX8v2-O4BQf8bs/WS-yLAbnDnQ4OTYY0vU9jXQ9skqpqRfa3yOg4yuE3wOWOyygA3ep6dFiXWgYSLga3OckI5N5NgfiZ9-L6f0uP4z3gqQzxHEhReBJzr4tv4vOpooYyc7Zs9xvM25ucWxQ/IGOXcGiNK06JHGB2zVPPPWDh642iJ01aL7LBVgDNxabtE_kaM67Dzoml0hfzW79mlIvD_BhoO4oht4St3GDvHSOyanx4d289evIuciIuvGbs5IajNiEUg4jzYB_Hhj7L/zqpLNmWpKOygUxpVdhVGui8tQ0sg2IL-bvpPwXDaAeKljJSEqB894_3mCI7XXfuydofOwnaIH2GYu5Xrapsf5AqlcSIqMX3LfMtP2-gizV2mTUpiAVOiETdiIyusIbl7/ga8lB26xyAF_Mb4cRRrxovMYOOMzwHUC4Nm32WC-2kxBIU7DGMbwk8z3WNdZ-j5zS6CfhOl50IeickAo4USXTaDVsH9GL9V9-94_upRWXn37NNAc_qlBU2AqCTszwRwi/aqx07tdaz-mHQcQvSh-FniWUZHwwYNobJyEzsmkaSd894W6inzJtVcN7CWFuV4HdxvzfBAMKQBow7LI7oNz_tHVeOf0bjQiv5fwB9dRGvRE6ScW6TcFx99DcxXjsJXxt/5ddiP2Z8WddjhGkTut70RyvrtMmKigzn5X_yVPysGGcevQDaY8E7orTeO8Dpv23zR7DFr2vg2Vb5jpjDP7CZrw/master.m3u8?anvtrid=157dba69077122cf7996ae732636ed99&anvauth=tb=0~te=1560472481~sgn=83258ec5a9705179d1cb17e3548d356588720e4459f4e7c0da0d12adcdc9d5e7&t=1560472391&_vpng=0` |
| +3 |  |  | `www.kob.com` | 1 | image | `https://www.kob.com/favicon.ico?v=ng9jm3Ropr` |
| +3 |  |  | `www.kob.com` | 1 | other | `https://www.kob.com/site.webmanifest?v=ng9jm3Ropr` |
| +3 |  |  | `www.facebook.com` | 3,1 | image | `https://www.facebook.com/common/cavalry_endpoint.php?t_cstart=1560472384085&t_start=1560472384085&t_domcontent=1560472384108&t_layout=1560472384112&t_onload=1560472384112&t_paint=1560472384112&t_creport=1560472384112&t_tti=1560472384108&lid=6702177887748056857-0` |
| +3 |  |  | `www.facebook.com` | 3,1 | inline-script | `https://www.facebook.com/v2.11/plugins/like.php?action=recommend&app_id=107596302633663&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D44%23cb%3Df991e62f61c7ec%26domain%3Dwww.kob.com%26origin%3Dhttps%253A%252F%252Fwww.kob.com%252Ff18b84bcb62f7c8%26relation%3Dparent.parent&container_width=663&href=https%3A%2F%2Fwww.kob.com%2Falbuquerque-news%2Fpolice-investigating-rainbow-crosswalk-vandalism-as-possible-hate-crime%2F5380398%2F&layout=button&locale=en_US&sdk=joey&share=true&show_faces=false&size=large` |
| +3 |  |  | `www.facebook.com` | 3,3 | xhr | `https://static.xx.fbcdn.net/rsrc.php/v3iEpO4/yR/l/en_US/dQTAGopOx3X.js` |
| +3 |  |  | `www.facebook.com` | 3,3 | image | `https://static.xx.fbcdn.net/rsrc.php/v3/yM/r/vle-6xM0Vx5.png` |
| +3 |  |  | staticxx.facebook.com | 3,1 | inline-script | `https://staticxx.facebook.com/connect/xd_arbiter.php?version=44#channel=f18b84bcb62f7c8&origin=https%3A%2F%2Fwww.kob.com` |
| +2 |  |  | `www.kob.com` | 3 | xhr | `https://tkx.apis.anvato.net/rest/v2/mcp/video/4673201?anvack=YVdnkAXpYxdJ8s9xLxUeeSOW9V9ALlJ9&anvtrid=wb80254a9855784c19c6988ae&rtyp=fp&X-Anvato-Adst-Auth=LguoOItg0Hm6%2BD8LDd4Ib%2F%2FlBD%2Ffsn6vOAWeav376GrIntui4HCSuLWkOwyCeuLyrcLp0j6Df5lD%2Fg012%2Ffcmg%3D%3D` |
| +2 |  |  | `www.kob.com` | 3 | image | `https://www.facebook.com/tr/?id=1886683388032937&ev=PageView&dl=https%3A%2F%2Fwww.kob.com%2Falbuquerque-news%2Fpolice-investigating-rainbow-crosswalk-vandalism-as-possible-hate-crime%2F5380398%2F&rl=&if=false&ts=1560472383963&sw=1920&sh=1080&v=2.8.52&r=stable&ec=0&o=30&fbp=fb.1.1560472339031.1871486725&it=1560472383745&coo=false&rqm=GET` |
| +2 |  |  | `www.kob.com` | 3 | frame | `https://www.facebook.com/v2.11/plugins/like.php?action=recommend&app_id=107596302633663&channel=https%3A%2F%2Fstaticxx.facebook.com%2Fconnect%2Fxd_arbiter.php%3Fversion%3D44%23cb%3Df991e62f61c7ec%26domain%3Dwww.kob.com%26origin%3Dhttps%253A%252F%252Fwww.kob.com%252Ff18b84bcb62f7c8%26relation%3Dparent.parent&container_width=663&href=https%3A%2F%2Fwww.kob.com%2Falbuquerque-news%2Fpolice-investigating-rainbow-crosswalk-vandalism-as-possible-hate-crime%2F5380398%2F&layout=button&locale=en_US&sdk=joey&share=true&show_faces=false&size=large` |
| +2 |  |  | `www.kob.com` | 3 | xhr | `https://tkx.apis.anvato.net/rest/v2/server_time?anvack=YVdnkAXpYxdJ8s9xLxUeeSOW9V9ALlJ9&anvtrid=wf9cf9f57c899eefa343d7337` |
| +2 |  |  | `www.kob.com` | 1 | inline-script | `https://www.kob.com/albuquerque-news/police-investigating-rainbow-crosswalk-vandalism-as-possible-hate-crime/5380398/` |
| +2 |  |  | `www.kob.com` | 3 | xhr | `https://access-prod.apis.anvato.net/anvacks/YVdnkAXpYxdJ8s9xLxUeeSOW9V9ALlJ9?apikey=3hwbSuqqT690uxjNYBktSQpa5ZrpYYR0Iofx7NcJHyA` |
| +2 |  |  | `www.kob.com` | 3 | frame | `https://staticxx.facebook.com/connect/xd_arbiter.php?version=44#channel=f18b84bcb62f7c8&origin=https%3A%2F%2Fwww.kob.com` |
| +2 |  |  | `www.kob.com` | 3 | script | `https://connect.facebook.net/signals/plugins/inferredEvents.js?v=2.8.52` |
| +2 |  |  | `www.kob.com` | 3 | image | `https://www.facebook.com/tr/?id=107596302633663&ev=fb_page_view&dl=https%3A%2F%2Fwww.kob.com%2Falbuquerque-news%2Fpolice-investigating-rainbow-crosswalk-vandalism-as-possible-hate-crime%2F5380398%2F&rl=&if=false&ts=1560472383837&sw=1920&sh=1080` |
| +2 | \|\|lightboxcdn.com^ | -- | `www.kob.com` | 3 | script | `https://www.lightboxcdn.com/vendor/3dd9a877-fb18-4b6d-ac35-a0d9adcf9923/lightbox.js?mb=1560472383819&lv=1` |
| +2 | \|\|scorecardresearch.com^ | -- | `www.kob.com` | 3 | script | `https://sb.scorecardresearch.com/beacon.js` |
| +2 | \|\|quantserve.com^ | -- | `www.kob.com` | 3 | script | `https://secure.quantserve.com/quant.js` |
| +2 | \|\|google-analytics.com^ | -- | `www.kob.com` | 3 | script | `https://www.google-analytics.com/analytics.js` |
| +2 | \|\|circularhub.com^ | -- | `www.kob.com` | 3 | script | `https://api.circularhub.com/7495/572bbeac30fdc02b/circularhub_module.js?_=1560472383593` |
| +2 |  |  | `www.kob.com` | 3 | script | `https://connect.facebook.net/signals/config/1886683388032937?v=2.8.52&r=stable` |
| +2 |  |  | `www.kob.com` | 3 | script | `https://connect.facebook.net/en_US/sdk.js?hash=3f561cf215fa54b7374583fef5b2944f&ua=modern_es6` |
| +2 |  |  | `www.kob.com` | 3 | script | `https://w3.cdn.anvato.net/player/prod/v3/28ukuji5h159q/scripts/anvplayer.min.js` |
| +2 |  |  | `www.kob.com` | 3 | css | `https://w3.cdn.anvato.net/player/prod/v3/28ukuji5h159q/anvhtml5.css` |
| +2 | \|\|googleadservices.com^ | -- | `www.kob.com` | 3 | script | `https://www.googleadservices.com/pagead/conversion.js` |
| +2 | \|\|adsrvr.org^ | -- | `www.kob.com` | 3 | script | `https://js.adsrvr.org/up_loader.1.1.0.js` |
| +2 | \|\|addthis.com^ | -- | `www.kob.com` | 3 | script | `https://s7.addthis.com/js/300/addthis_widget.js#pubid=kobwebmaster` |
| +2 |  |  | `www.kob.com` | 3 | script | `https://connect.facebook.net/en_US/fbevents.js` |
| +2 |  |  | `www.kob.com` | 3 | script | `https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.11&appId=107596302633663&autoLogAppEvents=1` |
| +2 | \|\|googletagservices.com^ | -- | `www.kob.com` | 3 | script | `https://www.googletagservices.com/tag/js/gpt.js` |
| +2 | \|\|widgets.outbrain.com^ | -- | `www.kob.com` | 3 | script | `https://widgets.outbrain.com/outbrain.js` |
| +2 |  |  | `www.kob.com` | 1 | image | `https://www.kob.com/2016/images/search.png` |
| +2 | \|\|googlesyndication.com^ | -- | `www.kob.com` | 3 | script | `https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js` |
| +2 | \|\|videoplayerhub.com^ | -- | `www.kob.com` | 3 | script | `https://kob-cdn-us.videoplayerhub.com/galleryloader.js` |
| +2 | \|\|boomtrain.com^ | -- | `www.kob.com` | 3 | script | `https://cdn.boomtrain.com/analyticstrain/kob-hubbard-tv/analyticstrain.min.js` |
| +2 |  |  | `www.kob.com` | 1 | script | `https://www.kob.com/2016/scripts/ANVATO-Setup-Category-Xref-Playlist.js` |
| +2 |  |  | `www.kob.com` | 1 | script | `https://www.kob.com/2016/widgets/HBI-weatherWidgetDefault.js` |
| +2 |  |  | `www.kob.com` | 1 | script | `https://www.kob.com/2016/widgets/2016-WXWIDGET.js` |
| +2 |  |  | `www.kob.com` | 1 | css | `https://www.kob.com/assets/css/hbi.css` |
| +2 |  |  | `www.kob.com` | 1 | css | `https://www.kob.com/assets/css/brand.css` |
| +2 |  |  | `www.kob.com` | 1 | css | `https://www.kob.com/assets/css/hubbard-min.css` |
| +2 |  |  | `www.kob.com` | 1 | doc | `https://www.kob.com/albuquerque-news/police-investigating-rainbow-crosswalk-vandalism-as-possible-hate-crime/5380398/` |
| +2 |  |  | `www.kob.com` | 3 | xhr | `https://snqusdnbgfofq3fjdco7hofysc.gcdn.anvato.net/ua_hubbard_kob/480/19/06/06/4673201/5A693A1EE16DFF284437D33D3C9DA0E5835A2D8116BCF96C-6.ts?Expires=1560493984&KeyName=mcpkey1&Signature=qHnDRYAScf8gBACmKNxepyqYogI` |
| +1 |  |  | `www.kob.com` | 3 | xhr | `https://snqusdnbgfofq3fjdco7hofysc.gcdn.anvato.net/ua_hubbard_kob/480/19/06/06/4673201/5A693A1EE16DFF284437D33D3C9DA0E5835A2D8116BCF96C-5.ts?Expires=1560493984&KeyName=mcpkey1&Signature=AS65vgPGcsVjIU3o7d-VaKB4QOg` |
| +0 |  |  | `www.kob.com` | 3 | xhr | `https://snqusdnbgfofq3fjdco7hofysc.gcdn.anvato.net/ua_hubbard_kob/480/19/06/06/4673201/5A693A1EE16DFF284437D33D3C9DA0E5835A2D8116BCF96C-4.ts?Expires=1560493984&KeyName=mcpkey1&Signature=aNU-AB1k_-8LcJME9674gwVfs14` |
</details>

**Comment by AdroitAdorKhan** [comment]
Can you check now?

**Comment by terrorist96** [comment]
Fixed!
