### ISSUE TITLE
Domain '0' interfering with all urls containing 0

### ISSUE THREAD

**Issue by vexusia** [EnergizedProtection/block#195]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: EnergizedUltimate

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: ublockOrigin

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
0
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: uBlockOrigin

- Version: 1.20.0

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
As of today mainly due to a new install with the latest build of energizedUltimate in the filterlists, anything with a '0' in the domain name for any resource regardless of type or origin is being blocked. The '0' (zero) could be located anywhere within the url source and it will block the entire resource on every domain site with the exception of those whitelisted ofcourse. Naturally this tends to break almost every single website now. Confirmed on multiple devices with updated energized ultimate list.

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

<p align="center"><a href="https://saythanks.io/to/AdroitAdorKhan" target="_blank"><img src="https://img.shields.io/badge/Say%20Thanks-!-1EAEDB.svg?longCache=true&style=flat-square"></a><p>

**Comment by vexusia** [comment]
![Screenshot 2019-07-06 at 3 53 30 PM](https://user-images.githubusercontent.com/32143259/60760629-581c2c00-a006-11e9-9c2d-37ccb8bca2d1.png)
![Screenshot 2019-07-06 at 3 53 16 PM](https://user-images.githubusercontent.com/32143259/60760630-5bafb300-a006-11e9-9603-a2e61e262f49.png)

**Comment by vexusia** [comment]
Note: I have not tested other energized packs as I only use ultimate but it may be occurring in other packs also.

**Comment by L31FY** [comment]
I have this issue also. It's basically caused every page of every domain to be blocked to some horrible degree and I have to figure out by trial and error what to unblock to see what I need and still not be buggered with ads.

**Comment by vexusia** [comment]
![Screenshot 2019-07-06 at 5 09 10 PM](https://user-images.githubusercontent.com/32143259/60761461-ff08c400-a016-11e9-98d9-bc6cc558ba7b.png)
Fairly certain the issue is being caused by the first entry. Confirmed to be in the other energized packs too.

**Comment by L31FY** [comment]
It's definitely that first line with just the zero. I've accidentally added a user filter to ublock before by a messy keystroke and the exact same block everything behavior occurred. This actually had me look to see if I'd done that again maybe until I saw it came from this list.

**Comment by AdroitAdorKhan** [comment]
Sorry for this issue. Maybe you could try Adblock Filter on uBlock till the new update comes with the fix.

**Comment by AdroitAdorKhan** [comment]
Can you update to latest `.193` update and check again?

**Comment by vexusia** [comment]
Confirmed issue is fixed with latest update, Thank you. Attached screenshots for confirmation. Domains with 0 being allowed and problem entry in the source list is removed.

![Screenshot 2019-07-12 at 4 12 49 PM](https://user-images.githubusercontent.com/32143259/61155882-09680980-a4c0-11e9-8fe9-132211c2073c.png)
![Screenshot 2019-07-12 at 4 13 09 PM](https://user-images.githubusercontent.com/32143259/61155888-0d942700-a4c0-11e9-988b-3702fcc473f3.png)
