### ISSUE TITLE
Please remove indiewire.com, metacritic.com, collider.com from porn hosts

### ISSUE THREAD

**Issue by laserswift** [EnergizedProtection/block#2]
I don't think these sites are porn sites.

Thanks for your energizer collection. I use it on desktop and mobile. :)

**Comment by AdroitAdorKhan** [comment]
Hey! Sorry for the late response! Thanks for reporting. Will make sure to remove them from the Porn Lists.

**Comment by AdroitAdorKhan** [comment]
Sure. Would fix this on next release.
