### ISSUE TITLE
Yahoo.com

### ISSUE THREAD

**Issue by terrorist96** [EnergizedProtection/block#23]
https://www.yahoo.com/news/us-court-halts-construction-keystone-xl-oil-pipeline-072826935.html

![screenshot_20181111-112337_chrome](https://user-images.githubusercontent.com/12802056/48315448-56e44d80-e5a4-11e8-902d-f23aa2e68cdf.jpg)

**Comment by AdroitAdorKhan** [comment]
Help with the log kindly!

**Comment by terrorist96** [comment]
Can't reproduce anymore. It's now a standard ad that's being blocked not one of those full screen ads that appear as you scroll.

**Comment by terrorist96** [comment]
Seeing ads again.
![smartselect_20190115-201938_dnsfilter](https://user-images.githubusercontent.com/12802056/51220379-fc989d80-1902-11e9-9b4d-af5ef6b4793f.jpg)
![smartselect_20190115-201955_dnsfilter](https://user-images.githubusercontent.com/12802056/51220380-fc989d80-1902-11e9-8f99-5bb695f5f48a.jpg)

**Comment by terrorist96** [comment]
Link to ad:
`https://beap.gemini.yahoo.com/mbclk?bv=1.0.0&es=KuPC6JAGIS.scKjvBiXFfEym1DFInW.d9duAnLbj9XGwXN7mJ0._WhOGifzipoVjxiRoXpjHkBbNKFxmcuNCjdDS3WA5Q741cKzaamUFFcwlKWd1_WJOyjBApS3mW4X24IfKQAB3NQi5JF0JiWQdwZg0fRtNtCgD4rm6lgS3p6qctk4i5np4itkFEkshc4kCVDdpiJHQxArH.5A7ipgHnLSDfiQqgxEKHGByXGDusuzpE7rOCO03LiLDBpMLfx8QKSETpwZv8AAsldK7.vZkMti_WMQbMytwNyEQtVRqN.sAnMRZxq00ArssSZbSp2t7XHH5IoaUt4m7aIWPbRhHa2bED5IbAJmVrJnBlXAEWc_f_SJP7gEbbMXTdKQmdl0S3x0PwiEaGV4qn5RoeEXkIVQ8dnRHWJ_JyVry5r7hep.1YNS61fldtjkpHGB2FkWrHt4LptdgPslXlI3P14x_fZ1v5ypV8rcJejSt6maJWvPOzNJvBt4F8uR7UXQNDXrMs_3S98kjPbkX28.OPzT7zChqhHDojGNlz.zenfusO7Q8pE5EYObvh1yO_2bWhe0rx9Nk0a0-%26lp=`

**Comment by terrorist96** [comment]
I still see ads.

**Comment by AdroitAdorKhan** [comment]
Maybe another log check would be really helpful.

**Comment by terrorist96** [comment]
I can't get PDF to cooperate. I turned off blokada but keep seeing this web I restart PDF

```
EXCEPTION: java.io.InterruptedIOException: read interrupted
VPN Runner Thread terminated!
```

**Comment by AdroitAdorKhan** [comment]
Turn off Blokada Completely, and make sure the 'Always-On VPN' isn't turned on for Blokada/PDF. Once the Blokada is turned off, force stop and open PDF and that may help to grab the log.

**Comment by terrorist96** [comment]
I tried all that. Do you have an updated version of PDF you can send? I have 1.50.25

**Comment by AdroitAdorKhan** [comment]
You can knock the dev directly here, on their [Telegram Group](https://t.me/pDNSf).

**Comment by terrorist96** [comment]
Yeah it's not working for me. I downloaded the latest version. It's not blocking anything. I've checked the hosts, reloaded filter, restarted, confirm the VPN is running. Don't know what else to do.

**Comment by terrorist96** [comment]
I'll try Peter with ublock origin

**Comment by terrorist96** [comment]
Unfortunately can't reproduce with uBlock Origin on the computer, even if I spoof Android user agent. So no one else sees ads on yahoo? Just me?

**Comment by terrorist96** [comment]
Even on the home page:

![Screenshot_20190613-212650_Chrome](https://user-images.githubusercontent.com/12802056/59477192-1b537f80-8e22-11e9-9216-1bfc5b397073.jpg)

**Comment by AdroitAdorKhan** [comment]
I think it's gone now. Reopen if it's still there!

**Comment by terrorist96** [comment]
@AdroitAdorKhan unfortunately the ad is still there. And I don't see anything in the log that is allowed that could be blocked to block the ad.

**Comment by AdroitAdorKhan** [comment]
Can you send a screenshot of the ad? I can't find the ad here on my device.

**Comment by terrorist96** [comment]
![Screenshot_20190720-194029_Chrome](https://user-images.githubusercontent.com/12802056/61585315-51250b80-ab26-11e9-89b9-b82cde43b3c3.jpg)
![Screenshot_20190720-194048_Chrome](https://user-images.githubusercontent.com/12802056/61585316-51bda200-ab26-11e9-8a1b-5de334acbc0b.jpg)

**Comment by terrorist96** [comment]
> Link to ad:
> `https://beap.gemini.yahoo.com/mbclk?bv=1.0.0&es=KuPC6JAGIS.scKjvBiXFfEym1DFInW.d9duAnLbj9XGwXN7mJ0._WhOGifzipoVjxiRoXpjHkBbNKFxmcuNCjdDS3WA5Q741cKzaamUFFcwlKWd1_WJOyjBApS3mW4X24IfKQAB3NQi5JF0JiWQdwZg0fRtNtCgD4rm6lgS3p6qctk4i5np4itkFEkshc4kCVDdpiJHQxArH.5A7ipgHnLSDfiQqgxEKHGByXGDusuzpE7rOCO03LiLDBpMLfx8QKSETpwZv8AAsldK7.vZkMti_WMQbMytwNyEQtVRqN.sAnMRZxq00ArssSZbSp2t7XHH5IoaUt4m7aIWPbRhHa2bED5IbAJmVrJnBlXAEWc_f_SJP7gEbbMXTdKQmdl0S3x0PwiEaGV4qn5RoeEXkIVQ8dnRHWJ_JyVry5r7hep.1YNS61fldtjkpHGB2FkWrHt4LptdgPslXlI3P14x_fZ1v5ypV8rcJejSt6maJWvPOzNJvBt4F8uR7UXQNDXrMs_3S98kjPbkX28.OPzT7zChqhHDojGNlz.zenfusO7Q8pE5EYObvh1yO_2bWhe0rx9Nk0a0-%26lp=`

Clicking on them leads to the above domain which is blocked

**Comment by AdroitAdorKhan** [comment]
As per my test, the ads aren't from a different source. They are from the same image sources of yahoo. So there isn't any way to block them without breaking yahoo.

I will keep an eye though.
