### ISSUE TITLE
False positives

### ISSUE THREAD

**Issue by anonymous1184** [EnergizedProtection/block#242]
### Issue

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack

- Energized Ultimate 

<hr>

### Extension

- Energized Regional 

<hr>

### Domains
```
- Regional
  - ip-adress.com
  - netdna-cdn.com
- Ultimate
  - awemwh.com
  - bootstrapcdn.jdorfman.netdna-cdn.com
  - netdna-cdn.com
    - oss.maxcdn.com
    - www.maxcdn.com
  - ip-adress.com
  - www.ip-adress.com
  - zobj.net
```
<hr>

### Config

- Client: dnscrypt-proxy
- Version: 2.0.25

<hr>

### Details

- `[www.]ip-adress.com` is a functional site, misspelled intentionally.
- Twitter's Bootstrap uses StackPath (formerly MaxCDN, formerly netDNA). With `netdna-cdn.com` as root domain several rules become useless.
![img01](https://user-images.githubusercontent.com/53758552/63114152-b4556280-bf59-11e9-9083-d3b0da60396d.jpg)
- `oss.maxcdn.com` became (and redirects to) jsDelivr (Open Source CDN)
- `www.maxcdn.com` redirects to `https://www.stackpath.com/maxcdn/`
- `zobj.net` is a domain used by Zedge to provide media storage
- `awemwh.com` is an adult site CDN (maybe move the rule to Porn pack?)

**Comment by DRSDavidSoft** [comment]
@AdroitAdorKhan I think the reason that `ip-adress.com` is blocked in Energized is that the ABP-parsing scripts take domains with `third-party` flag into account. (This flag means that the domain name _should not_ be blocked itself, but any requests originating from other domains _to it_ should be blocked).

See here: https://github.com/AdguardTeam/AdguardFilters/blob/34f09d1b8c118d40a32dc5d35ceb618ccbee6332/SpywareFilter/sections/tracking_servers.txt#L1439

**Comment by DRSDavidSoft** [comment]
### whitelisting request
```
netdna-cdn.com
netdna-ssl.com
```

### example urls:
```
https://thewindowsclub-thewindowsclubco.netdna-ssl.com/wp-content/themes/TwcMetro/style.css
```

from this url: ```https://www.thewindowsclub.com/disable-google-chrome-software-reporter-tool#targetText=Software%20Reporter%20Tool%20is%20a,that%20may%20conflict%20with%20it.```

**Comment by DandelionSprout** [comment]
It appears to me that all 11 domains mentioned in this thread have either been added to Energized Unblock, which is the centralised whitelist, or are gone entirely, so this seems like a solved case to me.
