### ISSUE TITLE
Duolingo

### ISSUE THREAD

**Issue by terrorist96** [EnergizedProtection/block#25]
Unblocked ad in Duolingo
https://play.google.com/store/apps/details?id=com.duolingo
https://www.reddit.com/r/duolingo/comments/5mf7sn/ads_on_duolingo_is_this_new/

**Comment by AdroitAdorKhan** [comment]
Can you kindly help with the log? I see Google Ads could be the reason. As your region is different, I couldn't reproduce it.

**Comment by terrorist96** [comment]
![smartselect_20181113-185127_dnsfilter](https://user-images.githubusercontent.com/12802056/48450689-34edf500-e775-11e8-86e2-a9779e902df3.jpg)

**Comment by terrorist96** [comment]
Seems like it's Facebook.

**Comment by terrorist96** [comment]
Adding `graph.facebook.com` seems to have fixed it for me. I don't know if it will break legitimate content though.

**Comment by AdroitAdorKhan** [comment]
Then that's it! Blocking that Graph Facebook may break Facebook Apps.

**Comment by terrorist96** [comment]
If you know it will break legitimate stuff then probably best not to add it.
