### ISSUE TITLE
A few Facebook and Google tracking domains are missing

### ISSUE THREAD

**Issue by ghost** [EnergizedProtection/block#266]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name:
Spark

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
www.connect.facebook.net
connect.facebook.net
www.ssl.google-analytics.com
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: Magisk Module and hosts file (Windows 10)

- Version: 19.09.263

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
There are a couple tracker domains that are not included. They are for tracking purposes only and do not affect the use of the website. Domains belongs to Facebook and Google.

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

<p align="center"><a href="https://saythanks.io/to/AdroitAdorKhan" target="_blank"><img src="https://img.shields.io/badge/Say%20Thanks-!-1EAEDB.svg?longCache=true&style=flat-square"></a><p>

**Comment by AdroitAdorKhan** [comment]
There was report from our users about `connect.facebook.net`. Afaik, blocking this domain breaks few Facebook services. If you need full tracking protection, kindly use our Xtreme Protection pack.

**Comment by AnthonyKL** [comment]
@AdroitAdorKhan 

Does `www.ssl.google-analytics.com` break something?

**Comment by AdroitAdorKhan** [comment]
@AnthonyKL Sorry for late reply! But `ssl.google-analytics.com` is already blocked. So I think, `www.ssl.google-analytics.com` should also be blocked by that domain.

**Comment by AnthonyKL** [comment]
> @AnthonyKL Sorry for late reply! But `ssl.google-analytics.com` is already blocked. So I think, `www.ssl.google-analytics.com` should also be blocked by that domain.

Seems so.

I think this issue can be closed because the OP 's account has also been deleted.
