### ISSUE TITLE
Survey.forseeresults.com

### ISSUE THREAD

**Issue by terrorist96** [EnergizedProtection/block#28]
Whitelist survey.forseeresults.com

**Comment by terrorist96** [comment]
@AdroitAdorKhan still broken for me

**Comment by AdroitAdorKhan** [comment]
This domain/site itself is broken.

**Comment by terrorist96** [comment]
Says under construction, but loads. Enabling adblock just says can't find the IP.
https://survey.foreseeresults.com/survey/pages/thankyou/EmailResult.jsp?msg=Your+response+to+this+survey+has+already+been+accepted.+We+thank+you+for+your+participation%21

**Comment by AdroitAdorKhan** [comment]
Alright! Will fix them!

**Comment by terrorist96** [comment]
@AdroitAdorKhan
