### ISSUE TITLE
Hangouts and Messages broken

### ISSUE THREAD

**Issue by Kastilo** [EnergizedProtection/block#30]
Filter: Ultimate Protection - No extensions
OS: Ubuntu 18.04

Issue: The sites https://hangouts.google.com/ and https://messages.android.com/ are blocked with the filters, even with being whitelisted they are still treated as blocked outright
**EDIT**: Most google sites affected, including the Chrome Web Store

Temp fix: Clearing hosts file, not applying Energized Protection

**Comment by Kastilo** [comment]
EDIT: Breaks other site functions out of random, again clearing seems to get rid of all issues

**Comment by AdroitAdorKhan** [comment]
Can you help us with the log? Cause I see nothing wrong here on my devices.
