### ISSUE TITLE
whitelist needed for firestick to function properly

### ISSUE THREAD

**Issue by Thomas499** [EnergizedProtection/block#310]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: https://raw.githubusercontent.com/EnergizedProtection/block/master/ultimate/formats/hosts.txt

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: ultimate

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
api.amazonalexa.com 
dcape-na.amazon.com 
arcus-uswest.amazon.com
msh.amazon.com // <- Note: make a judgement call on this one. See details. 
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: 

- Version: 

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
**api.amazonalexa.com** // needed to setup a new firestick. Without it whitelisted, after you register the network name and password so that the firestick is connected to the internet, and after the first update completes, you can never finish the setup process it will get stuck on this page. 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/38442058/68780292-ee7ee080-05ea-11ea-9636-4d4f6e853358.png">

**If api.amazonalexa.com is whitelisted** it will continue to the page that says "Your Amazon Fire TV Stick 4K is registered to (owners name) Do you want to use this account?"

Once the firestick is setup (even if it was setup on a different network then transported to the new network where api.amazonalexa.com is blocked) then the firestick appears to work properly (in my experience so far). Would never know there was a problem with this url if the room mate hadn't factory reset the firestick by mistake and I had to re-register it. **Note:** If you just de-register the firestick and re-sign back into an account, this problem doesn't happen. For the issue to occur  you have to reset to factory default or use a new firestick.

**dcape-na.amazon.com** // needed to find apps. For example, if you type in hbo go in the search bar without dcape-na.amazon.com whitelisted it will pull up Movies and TV category and Search in Apps category which doesn't list the hbo go app as shown below.
<img width="689" alt="image" src="https://user-images.githubusercontent.com/38442058/68780564-56cdc200-05eb-11ea-957d-301d5e472ff3.png">

**If dcape-na.amazon.com is whitelisted** then it will additionally pull up an App and Games category where the HBO GO app is listed. 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/38442058/68780605-6816ce80-05eb-11ea-8e17-a7bf264531d3.png">

**Note**: to repeat this issue, you must go to manage install applications and clear data for Appstore, otherwise previous searches will show up as apps and the apps you previously searched for before 
dcape-na.amazon.com was blacklisted will still show up as options to download. 

In addition, without dcape-na.amazon.com whitelisted the firestick may be the cause for on occasion pull up a screen that says "An authentication error has occurred." This particular authentication error only happened once and I believe it happened when I typed in "Starz" in the search bar to look for the app to download. 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/38442058/68781051-0a36b680-05ec-11ea-9046-58e8ff5ddca5.png">

Without **arcus-uswest.amazon.com** whitelisted the firestick will not show you your downloaded apps on the homepage where it says "recent" category and "your apps and channels" category. 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/38442058/68780884-c774de80-05eb-11ea-8adb-33166fc67f20.png">

**arcus-uswest.amazon.com whitelisted** it shows "recent" list and "your apps and channels" list as shown below
<img width="689" alt="image" src="https://user-images.githubusercontent.com/38442058/68780985-eb382480-05eb-11ea-8f7f-41abf363947e.png">
**Note**: to repeat this issue, you must go to manage install applications and clear data for Appstore, Alexa shopping, and Prime Video.  Also, you will loose the order of your listed apps if you organized them previously. 

I also noticed without **msh.amazon.com** whitelisted, if you download an app it will get to about 90% of the download circle that shows you the status of the download and then freeze for about a minute as shown in the picture below.
<img width="387" alt="image" src="https://user-images.githubusercontent.com/38442058/68780497-3ef63e00-05eb-11ea-910c-250c5205b200.png">
Thus, instead of a 5 second download it takes about a minute to complete. However, other than taking longer to complete downloads I haven't notice any other issues yet with msh.amazon.com blacklisted. So probably would be a good idea to figure out what msh.amazon.com does. If it provides ads or tracking then keep it on the blocklist. If it doesn't do anything bad then whitelist it so the downloads are much faster. Make a judgement call on that one. 

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

<p align="center"><a href="https://saythanks.io/to/AdroitAdorKhan" target="_blank"><img src="https://img.shields.io/badge/Say%20Thanks-!-1EAEDB.svg?longCache=true&style=flat-square"></a><p>

**Comment by Thomas499** [comment]
Yesterday I de registered a firestick and today I re-registered it. To my surprise, I found that I ran into the same issue that I previously documented for api.amazonalexa.com but even though api.amazonalexa.com was whitelisted I still ran into the same problem and found that **whitelisting ftvr-na.amazon.com** fixed the problem this time. So I am now wondering if the firestick chooses a random server from the list and if it cant connect then it won't let you register the device?

**Comment by AdroitAdorKhan** [comment]
Hey! First of all, this is a nicely described issue you have made here! :) 

I don't have firestick to test physically, but with your well described info, it would be easier for me to find the solution! I will look more into this issue and try to fix asap.

**Comment by Thomas499** [comment]
It appears that all of the listed urls have since been whitelisted. I think the issue can now be closed.
