### ISSUE TITLE
assets/filters?

### ISSUE THREAD

**Issue by patrickdrd** [EnergizedProtection/block#316]
so what happened to assets/filters?
such as:
https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/converter/filter/

https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/converter/filter/adguard-dns.txt

?

**Comment by AdroitAdorKhan** [comment]
In last major update, I changed the directory, it's in `(/assets/sources/)` now and made the main script smarter enough to detect adblock/hosts format and filter them accordingly.
