### ISSUE TITLE
zdbb.net

### ISSUE THREAD

**Issue by terrorist96** [EnergizedProtection/block#32]
Whitelist zdbb.net.
Blocks links like
https://zdbb.net/tb/?http%3a%2f%2fwww.tkqlhce.com%2fclick-7511556-11497444-1428599469000%3fsid%3d__GUID__%26url%3dhttps%253a%252f%252fwww.samsung.com%252fus%252fshop%252fearly-black-friday%252f&item_type=deal&page=https%3A%2F%2Fwww.techbargains.com%2Fpromos%2Fblack-friday-deals%3Futm_source%3Dars%26source%3Dars&device=m&source=ars&item_id=429786&category=Black%2520Friday&vendor=Samsung&item_name=Samsung%2520Black%2520Friday%2520NOW%2520LIVE%253A%2520up%2520to%252050%2525%2520off%25204K%2520UltraHD%2520TVs%252C%2520Smartphones%252C%2520Smartwatches.%2520Tablets%2520%2526%2520more&original_name=Samsung%2520HDTV%2520Cyber%2520Monday%2520Sale%2520-%2520Year%2520End%2520Blowout%2520on%25202015%2520Models&author=eng&tracker=ars_promo_Samsung_1123_429786&zd_ptax=444&click_attribution=deal_429786&price=Roundup&clickGuid=__GUID__

**Comment by terrorist96** [comment]
Also need to whitelist the following to fix that link

www.tkqlhce.com
cj.dotomi.com
www.emjcd.com

**Comment by AdroitAdorKhan** [comment]
These are adv sources. Sorry! Can't whitelist these.

**Comment by terrorist96** [comment]
Too bad.
