### ISSUE TITLE
nfl.com

### ISSUE THREAD

**Issue by terrorist96** [EnergizedProtection/block#321]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: blu

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
api.nfl.com
(www.)googletagservices.com
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: 

- Version: 

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

`http://www.nfl.com/videos/nfl-game-highlights/0ap3000001080506/Haskins-celebrates-first-win-as-starter-by-taking-selfie-with-fans?videoId=10103061-7033-0000-0108-05066a7bb9f4`

`api.nfl.com` causes banner game scores to be blocked.
`www.googletagservices.com` causes video to not load. I don't think there's a way for you to whitelist this domain only on `nfl.com`?

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

**Comment by kah0922** [comment]
With host level blocking, it's all or nothing sadly. `api.nfl.com` seems to be a false positive, but `www.googletagservices.com` is notorious for both tracking and breaking sites when blocked. 

One way around this is using uBlock Origin, which will redirect `www.googletagservices.com` to a non-tracking version, without breaking the site.

I also highly discourage visiting any site that loads javascript that does not support https.

**Comment by AdroitAdorKhan** [comment]
Yes. As per @kah0922, I'm fixing the false positive, but `googletagservices` can't be whitelisted!
