### ISSUE TITLE
whitelist cnstrc.com

### ISSUE THREAD

**Issue by danmcc** [EnergizedProtection/block#324]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: Basic

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
cnstrc.com
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: None

- Version: n/a

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

Thank you for making energized.pro a great product. I would like to propose whitelisting `cnstrc.com` (which is in the `1hosts` and `1hosts-pro` lists).

`cnstrc.com` is a service domain for [Constructor.io](https://constructor.io), a search-as-a-service company. Constructor.io uses user behavior to personalize search results, but tracks users anonymously (by assigning them a random ID) and does NOT track them across sites -- the ID is specific to the site showing the search results. The service was specifically designed with user privacy in mind, and it does not serve ads (nor can it be used to serve ads), and of course not porn or malware either.

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

**Comment by kah0922** [comment]
`improving.duckduckgo.com` makes much of the same claims.
It's also blocked.
Regardless of whether it's anonymized or not, it's still a tracker.
