### ISSUE TITLE
Please convert energized hosts to filter.dat for supporting new bromite adblock filter 

### ISSUE THREAD

**Issue by qiforra** [EnergizedProtection/block#329]
can you convert your filter to new bromite filter format 
The documentation is this 
 https://www.bromite.org/custom-filters
Thanks

**Comment by AvinashReddy3108** [comment]
Looks great, does it also work for the Bromite webview tho?

**Comment by AdroitAdorKhan** [comment]
Chromium/Bromite Custom Filter support has been added!
