### ISSUE TITLE
Block

### ISSUE THREAD

**Issue by terrorist96** [EnergizedProtection/block#34]
Block:
whatsaappp.com
check-now.net
googlo.co
yahoo-news.co

![screenshot_20181125-133009_chrome](https://user-images.githubusercontent.com/12802056/48982917-760bd080-f0b6-11e8-8cfc-c74dbcc8a39d.jpg)

**Comment by terrorist96** [comment]
The subdomains aren't blocked.

**Comment by AdroitAdorKhan** [comment]
Their sub domain list is too big. And, we just blocked the main ones which popup first without any sub-domain.

**Comment by terrorist96** [comment]
Can't do wildcard like `*.whatsaappp.com`?

**Comment by AdroitAdorKhan** [comment]
Unfortunately no! Hosts doesn't support wildcard yet.

**Comment by terrorist96** [comment]
Will it in the future? Or not possible?

**Comment by terrorist96** [comment]
@AdroitAdorKhan

**Comment by terrorist96** [comment]
@AdroitAdorKhan

**Comment by AdroitAdorKhan** [comment]
No hosts won't support wildcard anytime soon, i guess!

**Comment by terrorist96** [comment]
> No hosts won't support wildcard anytime soon, i guess!

@AdroitAdorKhan 
Blokada now supports wildcard. So can Energized support it now?

**Comment by AdroitAdorKhan** [comment]
Well, I didn't know about Blokada update. I won't include wildcard support in hosts. Instead, I will create a separate wildcard/regex list for almost all the devices, apps or softwares that support them. Infact I have been thinking about this for a while. Let's see, soon! ;)
