### ISSUE TITLE
Microsoft Authenticator can't backup

### ISSUE THREAD

**Issue by t-makaro** [EnergizedProtection/block#340]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [x] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: Tried both Spark and Blu Go

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```

```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: Magisk Module

- Version: 

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

I noticed that my Microsoft Authenticator app had not backed up since Dec. 20th 2019. The day that I set up Energized Pro. Manually backing up fails. I disabled energized and it begun working again. Re-enabled with the Spark pack and it stopped working again.

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

**Comment by AdroitAdorKhan** [comment]
Can you check again and report back? I have checked from my side, and Authenticator app is working fine now.

**Comment by t-makaro** [comment]
![Screenshot_20200121-111047](https://user-images.githubusercontent.com/18018386/72835897-6c411700-3c40-11ea-80b8-6b3b994cdb10.png)

Unfortunately, it still does not work. Disabling energized fixes the problem.

**Comment by t-makaro** [comment]
It should be noted that the above screenshot occurs when attempting to turn off backup but not on. The backup appears to turn on correctly, but after a while (a few weeks) the app will try to backup again, but it fails and the app will ask (inside the menu) to sign in again to backup which then fails. 

I've managed to determine that ```activity.windows.com``` is the url that microsoft authenticator is needing that it blocked.

**Comment by AdroitAdorKhan** [comment]
It should be fixed now. Kindly check again.

**Comment by t-makaro** [comment]
No problems that I can see now!
