### ISSUE TITLE
Cryptocurrency sites

### ISSUE THREAD

**Issue by terrorist96** [EnergizedProtection/block#367]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: 

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
There are 10 next.exchange domains that should be removed.
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: 

- Version: 

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
It seems energized uses a list that blocks anything related to cryptocurrency. For example see #364 #206 #85 
Please consider removing this list as cryptocurrency related sites are not advertisements.

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

**Comment by terrorist96** [comment]
Also `namecoin.info` has 4 that should be removed.

**Comment by AdroitAdorKhan** [comment]
@terrorist96  Can you check the latest update, and let me know if those domains were whitelisted?

**Comment by terrorist96** [comment]
Yes, they are whitelisted now. But the bigger issue is that many more legitimate sites (that I haven't gone through) are still blocked because of the issue noted in #206

**Comment by bgiesing** [comment]
`freebitco.in` probably should also be whitelisted

**Comment by terrorist96** [comment]
@AdroitAdorKhan 
```
btc.com
m.btc.com
freebitco.in
```

We can continue to do this one by one or you can agree to remove the culprit coin block list that has significant false positives. Thanks.

**Comment by terrorist96** [comment]
`www.kano.is`

**Comment by terrorist96** [comment]
`s.btc.com`

**Comment by terrorist96** [comment]
`ghash.io`

**Comment by terrorist96** [comment]
`www.btc.top`

**Comment by terrorist96** [comment]
`btcc.com`

**Comment by terrorist96** [comment]
`bitfury.com`

**Comment by terrorist96** [comment]
`bytepool.com`

**Comment by terrorist96** [comment]
`slushpool.com`

**Comment by terrorist96** [comment]
`www.poolhb.com`

**Comment by terrorist96** [comment]
```
viabtc.com
www.viabtc.com
static.viabtc.com
```

**Comment by terrorist96** [comment]
```
www.antpool.com
v3.antpool.com
```

**Comment by terrorist96** [comment]
`pool.btc.com`

**Comment by terrorist96** [comment]
`doc.btc.com`

**Comment by terrorist96** [comment]
`static.f2pool.com`

**Comment by terrorist96** [comment]
`auroracoin.org`

**Comment by terrorist96** [comment]
`web.getmonero.org`
