### ISSUE TITLE
all lists empty

### ISSUE THREAD

**Issue by JonnyThree** [EnergizedProtection/block#369]
all lists empty

**Comment by arun54321** [comment]
Also the website isn't working....

**Comment by JonnyThree** [comment]
> 
> 
> Also the website isn't working....

yes i confirm also that 
i seriously hope that they dont desappear

**Comment by AdroitAdorKhan** [comment]
Website server was undergoing maintenance. It's live now. But the build issue is from VPS server. Hopefully it will be fixed soon. And, @JonnyThree nothing to worry about, we won't disappear!

**Comment by JonnyThree** [comment]
so many thanks for this fast support. This is the best source for adblocking, i really appreciate your work.

**Comment by AdroitAdorKhan** [comment]
Issues have been fixed! Everything is up and fine!
