### ISSUE TITLE
PUBG mobile block

### ISSUE THREAD

**Issue by LoreBadTime** [EnergizedProtection/block#372]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [x] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: Unified 

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: Xtreme

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```

```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: 

- Version: 

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: i needed to edit and remove some tencent cloud/related domains in order to start PUBG mobile,as for now using unified and xtreme blocks the game if host isnt edited 

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

**Comment by UnKnown-gamer** [comment]
> # Energized Protection - block ⚡
> **Let's make an annoyance free, better open internet, altogether!**
> ## Issue Submit Form
> Provide the following infos properly, which will help us to resolve your issue quickly.
> ### Issue(s):
> Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]`
> You can select more than one category of issues if you need to!
> 
> * [ ]  Whitelist
> * [ ]  Blacklist
> * [x]  App Broken
> * [ ]  Website Broken
> * [ ]  Request
> * [ ]  Other Issue
> 
> ### Pack(s):
> Write the name of the pack(s) you are using.
> 
> * Pack(s) Name: Unified
> 
> ### Extension(s):
> Also name the extension(s) if you are using any. If you don't then leave it blank.
> 
> * Extension(s) Name: Xtreme
> 
> ### Domain(s):
> If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.
> 
> * Domain(s):
> 
> ```
> 
> ```
> 
> ### Your Config:
> Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list.
> Make sure you are running Energized Protection Service only.
> 
> * Client:
> 
> * Version:
> 
> ### Details:
> Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.
> 
> * Your Issue Detail: i needed to edit and remove some tencent cloud/related domains in order to start PUBG mobile,as for now using unified and xtreme blocks the game if host isnt edited
> 
> ## Thank you for making Energized Protection great with your kind help!
> A project by [Ador](https://nayemador.com) with ❤

WTF

**Comment by AvinashReddy3108** [comment]
@LoreBadTime 
Please remove the "Xtreme" extension and switch to a smaller pack, like "BLU" or "BLU Go" for playing games on your device.

**Comment by LoreBadTime** [comment]
Thanks but i have alread6 modified the host ,i only deleted tencent related
apps

Il mar 10 mar 2020, 14:54 Avinash Reddy <notifications@github.com> ha
scritto:

**Comment by ashraf112** [comment]
if (std::find(playerIDs.begin(), playerIDs.end(), curActorID) != playerIDs.end())
{
    int64_t rootCmpPtr = _Reader->readType<int64_t>(curActor + 0x188);
    int64_t playerState = _Reader->readType<int64_t>(curActor + 0x3D0);
    Vector3 actorLocation = _Reader->readVec(rootCmpPtr + 0x2DC);
    Vector3 relativeRotation = _Reader->readVec(rootCmpPtr + 0x02DC); // <---- here

    // ...
    
    w_data["players"].emplace_back(json::object({ { "t", actorTeam }, {"hp", hp}, { "x", actorLocation.X },{ "y", actorLocation.Y }, {"r", relativeRotation.Y } })); // <---- and here
}

**Comment by AvinashReddy3108** [comment]
> if (std::find(playerIDs.begin(), playerIDs.end(), curActorID) != playerIDs.end())
> {
> int64_t rootCmpPtr = _Reader->readType<int64_t>(curActor + 0x188);
> int64_t playerState = _Reader->readType<int64_t>(curActor + 0x3D0);
> Vector3 actorLocation = _Reader->readVec(rootCmpPtr + 0x2DC);
> Vector3 relativeRotation = _Reader->readVec(rootCmpPtr + 0x02DC); // <---- here
> 
> ```
> // ...
> 
> w_data["players"].emplace_back(json::object({ { "t", actorTeam }, {"hp", hp}, { "x", actorLocation.X },{ "y", actorLocation.Y }, {"r", relativeRotation.Y } })); // <---- and here
> ```
> 
> }

Can you explain this?

**Comment by UnKnown-gamer** [comment]
WTF lol sorry I don't know!
