### ISSUE TITLE
Snapchat is not working at all after the latest update to the Basic pack.

### ISSUE THREAD

**Issue by Pak9999** [EnergizedProtection/block#374]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

### Issue(s):
- [ ] Whitelist
- [ ] Blacklist
- [x] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: Basic

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```

```

<hr>

### Your Config:

- Client: Magisk Module

- Version: 4.9

<hr>

### Details:

- Your Issue Detail: 
So a little info about my Snapchat. My snap had been missing some features for some while like locations, temp, speed etc. It was very weird. I always thought i was just some bug that snapchat had not fixed but yesterday 04.03.2020. I updated the pack and it completely stopped working. Inside Snapchat was blank and when i tried relogging i could not log in again. So i tried reinstalling snap witch did not fix it. I tried restoring a backup, did not fix it. Then i remembered i updated the Adblock. So i went in and changed from Basic to Blu. After the restart it worked as normal no more features missing or any other problems. I have not tried any other packs yet besides the Blu.

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

**Comment by scafroglia93** [comment]
There is not much support, I am opening a series of issues but there is no answer

**Comment by Pak9999** [comment]
Well at least i found a solution, if anyone else faces the same problem there is a solution. If the devs want to fix it they have at least an problem report.

**Comment by scafroglia93** [comment]
need log please

**Comment by AdroitAdorKhan** [comment]
> Well at least i found a solution, if anyone else faces the same problem there is a solution. If the devs want to fix it they have at least an problem report.

Can you grab a log?

> There is not much support, I am opening a series of issues but there is no answer

We had few issues recently. For active support, kindly join our Telegram group.

**Comment by DandelionSprout** [comment]
I am not sure if this issue report is actually about any kind of issue at all. It looks like it's just someone writing a story about his/her experiences about updating their filters.

So since I am to dramatically reduce the backlog of things that the Energized team needs to take care (Some of which are pretty critical), I'll declare this a closed case.
