### ISSUE TITLE
[IMPORTANT!] Serious bug on the "unified" filter!

### ISSUE THREAD

**Issue by David-H-1** [EnergizedProtection/block#377]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [x] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: Unified

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: uBlock origin

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
EXAMPLE:
https://translate.google.com/translate?sl=[original language]&tl=[destinated language]&u=pornhub.com [or other websites that are listed]
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: SwitchHosts!

- Version: 20.03.068

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail:  Serious bug! End-users can circumvent the filter via Google or other search engines' cache or "Translate this page" function, resulting filter useless. Very unsafe for users in organizations. Porn and explicit content still can be played on the cached or "translated" page.
Very unsafe for cooperate networks. Imagine if everyone employee or student can watch porn sites even though they have filters on router and  of Energized, how can they work or study properly? Please fix it ASAP!

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

**Comment by David-H-1** [comment]
@AdroitAdorKhan

**Comment by AvinashReddy3108** [comment]
Unfortunately, we're pretty limited to the capabilities of the hosts file (and browser extensions) on how they block stuff.

This is something Google should fix in their website translating service.

**Comment by David-H-1** [comment]
OK. Closing this issue now.
