### ISSUE TITLE
[Important!] [Action required!] Please UNBLOCK mail.163.com hw.mail.com email.163.com and all Netease mail services!

### ISSUE THREAD

**Issue by David-H-1** [EnergizedProtection/block#382]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name:Unified 

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name:uBlock origin 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
mail.163.com
email.163.com
hw.mail.163.com
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: Switchhosts Linux

- Version: 20.03.073

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
With the Unified pack enabled I could not even access to the famous Netease mail service (a.k.a 163 mail, 126 mail and so on) For Chinese users' sake, please unblock them!!! Otherwise Chinese users cannot access to their mailbox with your filter/hosts enabled.
Steps:
Open firefox
Input any of the three
 ```
mail.163.com 
hw.163.com
email.163.com
```
would only result in "connection failed"
These three sites are NOT any of the spam/porn/malware sites, but legit sites which many Chinese people access. So PLEASE UNBLOCK THEM ASAP!!!

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

**Comment by David-H-1** [comment]
@AdroitAdorKhan It is completely a legit webmail provider site. So please block it ASAP. Thank you!

**Comment by David-H-1** [comment]
@AdroitAdorKhan please unblock all the three websites. Thanks

**Comment by AdroitAdorKhan** [comment]
Sure. This will be fixed in next release.
