### ISSUE TITLE
boards.greenhouse.io

### ISSUE THREAD

**Issue by edoteee** [EnergizedProtection/block#384]
### Issue(s):

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: Blu

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
https://boards.greenhouse.io/
```

<hr>

### Your Config:

- Your Issue Detail: 

Not able to view boards.greenhouse.io
This problem is mainly for url's which have `.io`

**Comment by AdroitAdorKhan** [comment]
I don't think this domain is blocked.

**Comment by DandelionSprout** [comment]
I for one get redirected to `www.greenhouse.io` when I attempt to load the example site.

**Comment by DandelionSprout** [comment]
I can see `boards.greenhouse.io` and `greenhouse.io` in Energized Unblock now, which is the centralised whitelist, so this seems like a solved case to me.
