### ISSUE TITLE
hpHosts has been discontinued.

### ISSUE THREAD

**Issue by kah0922** [EnergizedProtection/block#398]
[https://forums.malwarebytes.com/topic/256701-what-happened-to-hphosts-website/?tab=comments#comment-1370003](https://forums.malwarebytes.com/topic/256701-what-happened-to-hphosts-website/?tab=comments#comment-1370003)

[https://github.com/uBlockOrigin/uBlock-issues/issues/971](https://github.com/uBlockOrigin/uBlock-issues/issues/971)

**Comment by AdroitAdorKhan** [comment]
We will keep using backups, till they get too many dead/inactive domains. They had a good list tbh!
