### ISSUE TITLE
Moddb.com

### ISSUE THREAD

**Issue by Marek33** [EnergizedProtection/block#409]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
<strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issues:

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [x] Other Issue

<hr>

### Pack:

Energized IP Extension

<hr>

### Extension:

uBlock Origin

<hr>

### Domain:

https://www.moddb.com/groups/c-c-paradise

<hr>

### Details:

The Energized IP Extension blocks certain images, on the Moddb. It happens, especially at this link, where is a lot of images blocked: https://www.moddb.com/groups/c-c-paradise

<hr>

**Comment by AdroitAdorKhan** [comment]
Can you help finding the IPs?

**Comment by Marek33** [comment]
@AdroitAdorKhan There doesn't seem to be an issue with the IPs, but with the **/8** filter.

**Comment by Marek33** [comment]
Fixed, in the newer version.
