### ISSUE TITLE
osm.tiles.lightningmaps.org

### ISSUE THREAD

**Issue by Marek33** [EnergizedProtection/block#411]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
<strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issues:

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [x] Other Issue

<hr>

### Pack:

Energized IP Extension

<hr>

### Extension:

uBlock Origin

<hr>

### Domain:

https://osm.tiles.lightningmaps.org/

<hr>

### Details:

https://osm.tiles.lightningmaps.org/ is a part of the https://www.lightningmaps.org/ website.

<hr>

**Comment by AdroitAdorKhan** [comment]
What's the issue here? Can you write a little more about the issue.

**Comment by Marek33** [comment]
@AdroitAdorKhan The problem is that Energized IP Extension has the **/8** in the filter, and with uBlock Origin on Hard Mode, it makes grey lines on the site, even if the needed sites are greylisted. When I disable Energized the issue is gone.

**Comment by Marek33** [comment]
Fixed, in the newer version.
