### ISSUE TITLE
A lot of broken websites

### ISSUE THREAD

**Issue by Marek33** [EnergizedProtection/block#414]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
<strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issues:

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [x] Other Issue

<hr>

### Pack:

**Energized IP List Extension** and **Energized Regional Extension**

<hr>

### Extension:

**uBlock Origin**

<hr>

### Domain:

A few examples: Github.com, KnowYourMeme, YouTube.com (with old layout), Languagetool.org, Pcgamingwiki.com, Ap-pro.ru, Crymods.net, Forum.worldofplayers.de and Worldofplayers.ru.

<hr>

### Details:

Any domain, which has **2** in its name or the name of any file on the website.

<hr>

**Comment by AdroitAdorKhan** [comment]
Seems to work fine here for me! Can you check the domain list if anything is being blocked? and report them here kindly.

**Comment by ShreyasGavhalkar** [comment]
I too have been facing problems in getting packages

**Comment by AdroitAdorKhan** [comment]
New URLs of the packs have been added. Updated via those URLs.

**Comment by Marek33** [comment]
@AdroitAdorKhan From what I remember, it probably happens only on the Iridium and Ungoogled, but I'm not sure, since it was a very long time, since I posted this issue, and meanwhile I have removed the filters. 

Can you tell me, which versions of which ones should I download? There are too many of them, and the links for them on the Filterlist doesn't work.

**Comment by Marek33** [comment]
@AdroitAdorKhan The problem with the **/2** filter is back, and it mainly happens on the Iridium and Ungoogled, which I use as a main browser, currently. It's only in the Energized IP List only thou.

**Comment by Marek33** [comment]
@AdroitAdorKhan  It seems that it was fixed meanwhile (along with the other filter problems, which I had), so thanks!
