### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by p1r473** [EnergizedProtection/block#421]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: 
Energized Basic Protection
Energized Blu Protection
Energized BluGo Protection
Energized Spark Protection
Energized Ultimate Protection

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s): 

```
e-geräteundhaus.com
polenböller-deutschland.com
reimageplus.com^document
www.telemetry.appex.bing.net:443
?????gur.com
??oo??le.com
crpt.livejasmin.com???
dis??ordapp.com
disc??rd.com
e-geräteundhaus.com
hackf??rums.com
hackf??rums.net
img??r.com
minecr??ft.com
r??dd??t.com
s??rahah.eu
s??rahah.pl
s??ype.com
sh??rt.co
sp??tify.com
twi??ter.com
y??utube.com
yo??t??be.co
yo??t??be.com
yo??tu.be
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: PiHole

- Version: 20.03.069

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
The following have invalid/illegal characters in them and should be cleaned up

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

**Comment by p1r473** [comment]
@AdroitAdorKhan still a few illegal/invalid domains exist:
e-geräteundhaus.com
polenböller-deutschland.com

```
  [i] Target: https://block.energized.pro/basic/formats/domains.txt
  [✓] Status: Retrieval successful
  [i] Received 497864 domains, 2 domains invalid!
      Sample of invalid domains:
      - e-geräteundhaus.com
      - polenböller-deutschland.com

  [i] Target: https://block.energized.pro/blu/formats/domains.txt
  [✓] Status: Retrieval successful
  [i] Received 169479 domains, 2 domains invalid!
      Sample of invalid domains:
      - e-geräteundhaus.com
      - polenböller-deutschland.com

  [i] Target: https://block.energized.pro/bluGo/formats/domains.txt
  [✓] Status: Retrieval successful
  [i] Received 105192 domains, 2 domains invalid!
      Sample of invalid domains:
      - e-geräteundhaus.com
      - polenböller-deutschland.com

  [i] Target: https://block.energized.pro/spark/formats/domains.txt
  [✓] Status: Retrieval successful
  [i] Received 46849 domains, 2 domains invalid!
      Sample of invalid domains:
      - e-geräteundhaus.com
      - polenböller-deutschland.com

  [i] Target: https://block.energized.pro/ultimate/formats/domains.txt
  [✓] Status: Retrieval successful
  [i] Received 687606 domains, 2 domains invalid!
      Sample of invalid domains:
      - e-geräteundhaus.com
      - polenböller-deutschland.com

```

**Comment by L1Cafe** [comment]
Those domains are valid, please check attached pictures.
<img width="838" alt="image" src="https://user-images.githubusercontent.com/1437297/83982142-53ea4400-a924-11ea-9eff-91d2168c46b7.png">
<img width="829" alt="image" src="https://user-images.githubusercontent.com/1437297/83982148-5d73ac00-a924-11ea-84ab-b6f752cd7ff5.png">

For more info: https://en.wikipedia.org/wiki/Internationalized_domain_name

**Comment by p1r473** [comment]
> Those domains are valid, please check attached pictures.
> <img alt="image" width="838" src="https://user-images.githubusercontent.com/1437297/83982142-53ea4400-a924-11ea-9eff-91d2168c46b7.png">
> <img alt="image" width="829" src="https://user-images.githubusercontent.com/1437297/83982148-5d73ac00-a924-11ea-84ab-b6f752cd7ff5.png">
> 
> For more info: https://en.wikipedia.org/wiki/Internationalized_domain_name

Did you type the domains out, or copy and paste them?
When I copy and paste them. exactly as I pasted them, they contained invalid characters.
I tried nslookuping both with 1.1.1.1 and 8.8.8.8.

C:\WINDOWS\system32>nslookup e-geräteundhaus.com 1.1.1.1
Server:  one.one.one.one
Address:  1.1.1.1

*** one.one.one.one can't find e-geräteundhaus.com: Non-existent domain

C:\WINDOWS\system32>nslookup polenböller-deutschland.com 1.1.1.1
Server:  one.one.one.one
Address:  1.1.1.1

*** one.one.one.one can't find polenböller-deutschland.com: Non-existent domain

**Comment by L1Cafe** [comment]
Seems like your nslookup (and mine, apparently) hasn't been compiled with IDN support.

```
└─[$] <> nslookup polenböller-deutschland.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

** server can't find polenb\195\182ller-deutschland.com: NXDOMAIN
```

```
└─[$] <> nslookup xn--polenbller-deutschland-zhc.com 8.8.8.8
Server:		8.8.8.8
Address:	8.8.8.8#53

Non-authoritative answer:
Name:	xn--polenbller-deutschland-zhc.com
Address: 172.67.134.235
Name:	xn--polenbller-deutschland-zhc.com
Address: 104.28.29.110
Name:	xn--polenbller-deutschland-zhc.com
Address: 104.28.28.110
```

If you first convert the IDN containining non-ASCII characters, it should resolve successfully. Note that both IDN and ASCII-only domains actually point to the same place.

[IDN conversion tool](https://www.verisign.com/en_GB/channel-resources/domain-registry-products/idn/idn-conversion-tool/index.xhtml)
[nslookup manual from Debian](https://manpages.debian.org/unstable/dnsutils/nslookup.1.en.html)

**Comment by TheNec** [comment]
Quoting myself:

> Those (internationalized) domains seem to be valid from user/application side but indeed they are not as they contain invalid letters (ömlauts in this case) while only letters from the modern latin alphabet (a-z) are allowed. Internationalized domains are translated from the browser/client to valid domain names and after that the valid domain ist passed to the dns infrastructure.
> 
> Hope that helps!

So please delete or rename those domains. Additonally please delete or rename "reimageplus.com^document" which is at least included in the ultimate list.

Thank you in advance!

**Comment by DandelionSprout** [comment]
I can't find any of the entries from the OP in Ultimate Protection anymore. Does that mean that this has been fixed and can be declared a closed case?

**Comment by p1r473** [comment]
I will double check within a few days and get back to you

**Comment by p1r473** [comment]
Confirmed
