### ISSUE TITLE
Emoji's are not visible in many websites.

### ISSUE THREAD

**Issue by EvilSpark** [EnergizedProtection/block#427]
### Issue(s):

- [x] Whitelist
- [x] Blacklist
- [x] Website Broken

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: Ultimate

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s): https://forum.xda-developers.com/android/software-hacking/keweon-privacy-online-security-t3681139

```

```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: Hosts/ Hblock with only one source ie energized ultimate

- Version: latest

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
Emoji's are not visible. They appear as square boxes. And it's not the fault of my unicode or any font since it starts appearing only after I enabled it in my hosts.

![060505](https://user-images.githubusercontent.com/30311089/81027751-7fe55600-8e9c-11ea-8fc0-558cdc1ecaf4.png)

![060505-1](https://user-images.githubusercontent.com/30311089/81027781-97bcda00-8e9c-11ea-80bd-9a2d661e1aab.png)

<hr>

https://forum.xda-developers.com/android/software-hacking/keweon-privacy-online-security-t3681139
visit this and scroll down. Things like bullets have turned into square boxes.

Even the emoji's Grammarly extension uses are not working.

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>

</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

**Comment by AvinashReddy3108** [comment]
![Screenshot_20200515_103442](https://user-images.githubusercontent.com/27774996/82013395-dd955180-9697-11ea-9d01-bdfd1cc08ac1.png)
Strange, even with the uBlock Origin turned off, the emojis/bullets don't come back.

**Comment by AdroitAdorKhan** [comment]
I couldn't reproduce this issue either. Emojis dont seem to work for me either way. It doesn't show up even if I turn off the uBlock. (Only on KeWeOn thread, I have checked) But emojis are working for me on other site. Can you send another website where you are facing the same issue?

**Comment by EvilSpark** [comment]
it was my fault. since other than this keewon website, every other thing was fixed by the additional install of emoji-ttf font from AUR.
