### ISSUE TITLE
Not updated & download 404

### ISSUE THREAD

**Issue by pkejval** [EnergizedProtection/block#430]
Blocklists are not updated since 20.04.2020 and download links are 404 (https://block.energized.pro/blu/formats/hosts). What is going on?

**Comment by AvinashReddy3108** [comment]
We are currently facing some isues with our servers and updating our hosts right now, do read the below articles for a better explanation.

https://t.me/EnergizedProtectionUpdates/63
https://t.me/EnergizedProtectionUpdates/64

We are trying our best to solve this and hopefully, be back on track soon.

**Comment by shafwan7** [comment]
just found out this post. and thank you. hope it will be fix ASAP. my device is now non-adblock . i love using Energized. Easy GUI

> 
> 
> We are currently facing some isues with our servers and updating our hosts right now, do read the below articles for a better explanation.
> 
> https://t.me/EnergizedProtectionUpdates/63
> https://t.me/EnergizedProtectionUpdates/64
> 
> We are trying our best to solve this and hopefully, be back on track soon.

**Comment by pkejval** [comment]
They solved it by hosting at Gitlab. (y)

Odesláno z mého Mi9
________________________________

**Comment by genevera** [comment]
I'm still getting 404s with GitHub

![Screenshot_20200516-154106](https://user-images.githubusercontent.com/12733137/82128764-82dd2200-978b-11ea-9dca-3bb95cdfa864.png)

**Comment by pkejval** [comment]
Ok, you are using magisk script. My issue was about this repo. You can use Adaway app with hosts file from this repo. You can find links in readme of this repo.

Odesláno z mého Mi9

________________________________

**Comment by Poincare1** [comment]
I also receive 404 Not Found error when trying to update the Unified.  The above comments say this is fixed, but a 404 Not Found seems to indicate it is not fixed. How can I update Unified?

**Comment by AdroitAdorKhan** [comment]
With new module update, the issue has been resolved.
