### ISSUE TITLE
Invalid domains

### ISSUE THREAD

**Issue by p1r473** [EnergizedProtection/block#438]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: 
https://energized.pro/mirror/gasb-pe.txt

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s): 

```
hashbag.cc:8688
my▒therw▒llet.com
m▒eth▒rwall▒t.com
server.com:1234
domain=myway.com
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: PiHole

- Version: 20.03.069

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
The following have invalid/illegal characters in them and should be cleaned up

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

**Comment by AdroitAdorKhan** [comment]
I have removed the source already because of being inactive for too long. Changes will be live on next update.

**Comment by AdroitAdorKhan** [comment]
Can you confirm if they are gone with latest update?

**Comment by p1r473** [comment]
@AdroitAdorKhan they are still there at https://energized.pro/mirror/gasb-pe.txt

**Comment by AdroitAdorKhan** [comment]
My bad. I was talking about the source getting removed. We won't provide anymore support for that. We have dropped the source from our lists.

**Comment by p1r473** [comment]
@AdroitAdorKhan still a few illegal/invalid domains exist:
```
  [i] Target: https://block.energized.pro/basic/formats/domains.txt
  [✓] Status: Retrieval successful
  [i] Received 497864 domains, 2 domains invalid!
      Sample of invalid domains:
      - e-geräteundhaus.com
      - polenböller-deutschland.com

  [i] Target: https://block.energized.pro/blu/formats/domains.txt
  [✓] Status: Retrieval successful
  [i] Received 169479 domains, 2 domains invalid!
      Sample of invalid domains:
      - e-geräteundhaus.com
      - polenböller-deutschland.com

  [i] Target: https://block.energized.pro/bluGo/formats/domains.txt
  [✓] Status: Retrieval successful
  [i] Received 105192 domains, 2 domains invalid!
      Sample of invalid domains:
      - e-geräteundhaus.com
      - polenböller-deutschland.com

  [i] Target: https://block.energized.pro/spark/formats/domains.txt
  [✓] Status: Retrieval successful
  [i] Received 46849 domains, 2 domains invalid!
      Sample of invalid domains:
      - e-geräteundhaus.com
      - polenböller-deutschland.com

  [i] Target: https://block.energized.pro/ultimate/formats/domains.txt
  [✓] Status: Retrieval successful
  [i] Received 687606 domains, 2 domains invalid!
      Sample of invalid domains:
      - e-geräteundhaus.com
      - polenböller-deutschland.com

```
