### ISSUE TITLE
Not an issue, needed feature

### ISSUE THREAD

**Issue by gmnabeel** [EnergizedProtection/block#469]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: 

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```

```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: 

- Version: 

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

First of all great work.
My issue is with whitelisting apps . Most apps are not revealing their hostnames and block us from using the app. It's very frustrating as we don't won't to lose either. If you can add an option to whitelist applications (or) create a notification tile from where we can turn ad blocker on & off

Thanks again, cheers

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by foray1010** [comment]
It is not the scope of DNS block list, EnergizedProtection is just a list of domain to block, nothing more
I suggest you could use https://nextdns.io with EnergizedProtection, you can then see in the log section what domain is blocked, if your app has issue, try whitelist the domain and consider to report back here.

**Comment by DandelionSprout** [comment]
Currently, Blokada, AdGuard for Android, and DNS66 have options to whitelist entire apps from being subject to them. For most other client tools, that'd be considerably more difficult.
