### ISSUE TITLE
Amazon Web Services S3 blocked

### ISSUE THREAD

**Issue by m3adow** [EnergizedProtection/block#47]
By debugging the failure of a Podcast download I found out that several AWS S3 base domains are blocked. As these are used for various purposes around the web, it probably breaks a lot more than only my podcast downloads. These are said domains:
```
s3.eu-central-1.amazonaws.com
s3.us-east-2.amazonaws.com
s3-us-west-1.amazonaws.com
s3-us-west-2.amazonaws.com
s3.amazonaws.com
```
While there might be bad stuff hosted in S3, the same could be said for Github and nobody blocks the Github base domain.

I also found some more domains, but I'm not 100% certain if those are AWS S3 base domains, so they could probably remain blocked:

```
s3-1.amazonaws.com
s3-2-w.amazonaws.com
s3-amazonaws.com
```

**Comment by m3adow** [comment]
Okay, Layer 8 problem, I figured it out. I applied Energized via AdAway some months ago and never reverted the change, while still utilizing the Magisk Module lateron. This lead to some strange effects, AWS S3 being blocked seems to be one of them (older list with errors perhaps?). As of now, it seems S3 is not blocked.

**Comment by k4rn8g3** [comment]
@m3adow So our new list doesn't cause the problem..

Am I correct ??

**Comment by AdroitAdorKhan** [comment]
Check after updating to latest update.

**Comment by m3adow** [comment]
Looks good to me. The base urls have been removed from unified and ultimate.
