### ISSUE TITLE
Please remove me from this list

### ISSUE THREAD

**Issue by CHEF-KOCH** [EnergizedProtection/block#48]
Hello,
I wasn't asked to be a part here of this project and I doubt you officially asked someone because I didn't saw any discussion. My GitHub page clearly mentioned that I don't allow commercial usage of my filter list. Since you use Paypal I see this as commercial because you _possible_ get money for other peoples work. Sometimes I manually edit/add thousands of lines myself (which can't be done with some tools).  The license you mention for my project "unknown" is wrong, my license is since day one ISC.

Thanks for respecting my wish.

Greetings,
CK

**Comment by AdroitAdorKhan** [comment]
Hey!

Sorry for the misunderstanding. But we don't use your pack for any commercial use. We just asked if anyone is interested in paying for our services. All our services and packs are free so far. 

Can you kindly check your mail?

**Comment by CHEF-KOCH** [comment]
Okay, I checked the eMail from today and I'm not a dickhead and I allow it explicitly for this project since I can understand your current situation, but it would be kind if you (once you're in a position) donate something back to the other projects (not even saying that I want something back) because maintaining and providing the list is a huge task and you are well aware of it.  

I'm closing here.

**Comment by AdroitAdorKhan** [comment]
Fine! Will be removed on next update.

**Comment by CHEF-KOCH** [comment]
No it's okay as said.

**Comment by quantumpacket** [comment]
See above issue reference.

So the plagiarizer accuses others of using his already taken without permission work. What a joke! This project should just tell you to bugger off.

**Comment by CHEF-KOCH** [comment]
If you think so, you must known, the guy which works for a [project that stole money from people](https://github.com/irungentoo/toxcore/issues/1379).

**Comment by k4rn8g3** [comment]
@quantumpacket If we really wanted to 'steal' hosts lines, we would'nt have placed the source names and their URL's in our README !!
would have also saved us a lot of effort in making the damn huge table !!

**Comment by quantumpacket** [comment]
@k4rn8g3 that message wasn't directed at you or this project. Read the referenced issue...it was directed at OP.

**Comment by k4rn8g3** [comment]
@quantumpacket Hm..
I guess we should close this before any shitstorm blows this to a whole new direction !!

😂😂
