### ISSUE TITLE
Http

### ISSUE THREAD

**Issue by lolinajdi** [EnergizedProtection/block#507]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: unified

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```

```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

Magisk
- Client: 

- Version: 1.3.2

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: hello when I applied unified pack its show me this:
Pack Downloadingwget:server returned error:Http/1.1 404 not Found
![SmartSelect_٢٠٢٠٠٧١٧-١٦٥٠١٣_Keep Notes](https://user-images.githubusercontent.com/65453926/87793193-9a995b00-c84d-11ea-97ec-543dfc483ed7.jpg)

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by rungitringit** [comment]
I'm unable to download multiple lists (I've been trying to find one which works) from https://block.energized.pro/basic/formats/ and keep getting **404 Not Found**

**Comment by rungitringit** [comment]
@lolinajdi could you edit the title of this ticket to something clearer?
Something like "http 404 not found" or "Unable to download lists - http 404"

Thanks!

**Comment by dimkr** [comment]
This also applies to other files, see https://travis-ci.org/github/dimkr/dohli/jobs/709188483#L747.

**Comment by dimkr** [comment]
Also, it's clearly evident that https://block.energized.pro/ points to the wrong server :)

**Comment by rungitringit** [comment]
> Also, it's clearly evident that https://block.energized.pro/ points to the wrong server :)

Well that's the URL I obtained from the main github page here!

**Comment by rungitringit** [comment]
This appears to have been an outage over the weekend only - during a website update.
As of today this problem doesn't happen.  This should be closed.
