### ISSUE TITLE
[!] Unblock ssl.gstatic.com and fonts.gstatic.com because it breaks Gmail login interface

### ISSUE THREAD

**Issue by David-H-1** [EnergizedProtection/block#512]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: Energized Xtreme extension

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: uBlock origin

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
ssl.gstatic.com
fonts.gstatic.com
gstatic.com
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: NextDNS (xtreme extension filter list)

- Version: (Newest on 2020-07-21)

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
These three domains are essential to make Google websites work. Blocking them will cause icons to disappear and buttons broken. Please fix ASAP!

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by winduptoy** [comment]
I personally want all of that Google stuff blocked...

@AdroitAdorKhan Maybe there's a way to separate out the whitelist so that people can choose what they want blocked?

**Comment by ofiala-a51** [comment]
Wanting to whitelist Google's tracking domains because it breaks **their** services is straight up dumb. If you care about privacy, you shouldn't be using Google's services in the first place and definitely not Gmail. It literally scans all of your incoming and outgoing emails, that's the very opposite of privacy.

**Comment by David-H-1** [comment]
The problem is if you block Google completely you will also block Play Store which prevents most people from downloading apps except if they side load from the browser or third party App Store like FDroid

**Comment by David-H-1** [comment]
> Wanting to whitelist Google's tracking domains because it breaks **their** services is straight up dumb. If you care about privacy, you shouldn't be using Google's services in the first place and definitely not Gmail. It literally scans all of your incoming and outgoing emails, that's the very opposite of privacy.

OK I have deleted the fucking Gmail now and they will no longer be able to track me.
