### ISSUE TITLE
Please remove all references of blacklist and whitellists, use "blocklist (denylist)" and "allowlist" instead

### ISSUE THREAD

**Issue by David-H-1** [EnergizedProtection/block#517]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [x] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: N/A

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: N/A

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
N/A
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: N/A

- Version: N/A

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

After the Black Lives Matter Movement in North America. Many large companies begin to remove references of blacklists and whitelists from their applications and user interfaces. So why don't you guys do the same? Those companies include Microsoft, Google, Mozilla and even NextDNS.

**Please replace blacklist with blocklist (denylist) and whitelist with allow list! Thank you!** 

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by dgrbl** [comment]
blacklist and whitelist have nothing to do with human beings.
For instance we blacklisted Marxist Communists in 1950's Hollywood, who were white, its definition is undesirable or unecessary, there was even a recent tv show named Blacklist, as the characters fit this definition. blacklist and whitelist have nothing to do with human beings, or human beings race or ethnicity. 

https://www.merriam-webster.com/dictionary/blacklist


https://m.imdb.com/title/tt2741602/

**Comment by toxicologist** [comment]
lol

**Comment by David-H-1** [comment]
OK. Since it is inactive for a long time and is controversial, closing it now.
