### ISSUE TITLE
whitelist link download from uc browser

### ISSUE THREAD

**Issue by 3xploiton3** [EnergizedProtection/block#528]
https://www.ucweb.com/

wap.uc.cn
img.ucweb.com
http://pdds.ucweb.com/download/newest/UCBrowser/en-us/101/354/PC_banner

**Comment by DandelionSprout** [comment]
I can see all 4 of those domains (in addition to `ucweb.com`) in Energized Unblock now, which is the centralised whitelist, so this seems like a solved case to me.
