### ISSUE TITLE
gearbest stylesheet and sofascore blocked by spark!

### ISSUE THREAD

**Issue by patrickdrd** [EnergizedProtection/block#53]
even though you removed some sources, the problems remain in spark
(after last time it was blocking firefox sync and facebook)!

the new ones I run into are gearbest stylesheet and sofascore,
amazing, who blocks those and why?
using all that many hosts and having to whitelist all the many entres seems useless, don't you think?

anyway, I searched spark sources I found no results,

so the above should be in those "black boxes" sources:
Ador Energized, Adguard Ads & Spyware, Easylist Adserver & Lite, EasyPrivacy, Fanboy Cookiemonster, LightSwitch Extended

really, where are the links for them?
does adguard and easylist have a hosts blocking solution online? because I think they are more "ublock"-like, also, amazing that "Fanboy Cookiemonster" is even there,
this is to be used specifically by users that use ublock or adguard,
cookie notices can't be blocked by hosts solutions of course

**Comment by AdroitAdorKhan** [comment]
1. For those blocked/broken sites ~ Just send us the log/domains that were blocked!
2. For [Energized Core](https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/active/filter/ador-energized.txt), [Adguard Mobile Ads](https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/active/filter/adguard-mobile-ads.txt) & [Mobile Spyware](https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/active/filter/adguard-mobile-spyware.txt), [EasyList Adservers](https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/active/filter/easylist-adservers.txt), [EasyList Lite](https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/active/filter/easylist-lite.txt) and [Fanboy Cookiemonster](https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/active/filter/fanboy-cookiemonster.txt)
3. EasyPrivacy and Lightswitch Extended was removed. I updated the readme before removing the hosts! (and, somehow I ended up forgetting to add them back!)
4. And For your kind information, we got advanced scripts to convert those non-hosts lists to hosts. Here is the script ~ [Energized Converter](https://github.com/EnergizedProtection/block/tree/master/assets/converter)
*. if you really think we are that dumb! kindly stop using Energized for real good! :)

**Comment by patrickdrd** [comment]
I don't think you're dumb, I wouldn't be here if I did,
I'm just trying to find out who is,
ok, thanks, give me a minute to check

**Comment by AdroitAdorKhan** [comment]
what I meant is! We are open! The scripts we use, the sources we use, all are open, and you can easily check everything right from our git. You should have checked everything before submitting an issue.
Take your time and help us with the logs.

**Comment by patrickdrd** [comment]
ok, got it, both the problems are here:
https://raw.githubusercontent.com/EnergizedProtection/block/master/assets/active/filter/ador-energized.txt

css.gbtcdn.com
gloimg.gbtcdn.com
uidesign.gbtcdn.com
www.sofascore.com
all of these should be whitelisted

**Comment by AdroitAdorKhan** [comment]
That's fine! Then we will look into this and fix with next release.

**Comment by patrickdrd** [comment]
actually there are a lot you've got to whitelist:

`activations.cdn.mozilla.net
appbrain.com
blocklist.addons.mozilla.org
broker-live.mozillamessaging.com
cdn.optimizely.com
code.cdn.mozilla.net
css.gbtcdn.com
data.mozilla.com
fhr.cdn.mozilla.net
fhr.data.mozilla.com
gloimg.gbtcdn.com
googletagmanager.com
googletagservices.com
input.mozilla.org
keepimg.com
mozsocial.cliqz.com
mywot.com
pipe.skype.com
push.services.mozilla.com
search.services.mozilla.com
self-repair.mozilla.org
services.addons.mozilla.org
shavar.services.mozilla.com
snippets.cdn.mozilla.net
snippets.mozilla.com
syndication.twimg.com
tiles.services.mozilla.com
www.googletagmanager.com
www.googletagservices.com
www.mywot.com
www.sofascore.com
`

one day before I found mywot.com was blocked,
just run a check on the above and tell me if he who creates this list is dumb or not
(or maybe he's.. drunk when he's creating it),
I won't be using this particular one anymore because I've run into many "accidents" and
things don't seem to be getting better, sorry
I don't like such lists anyway, neither do I like the one by jawz (mobileadtrackers),
because it contains many false positives too and it shouldn't be in spark in my opinion
