### ISSUE TITLE
webfarm-50.q4web.com is a CNAME for ir.ssrmining.com 

### ISSUE THREAD

**Issue by p1r473** [EnergizedProtection/block#535]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name:  Ultimate, basic

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
webfarm-50.q4web.com
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: PiHole

- Version: 5.0

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
webfarm-50.q4web.com is a CNAME for ir.ssrmining.com 
This is a valid precious metals mining website.

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by n8v8R** [comment]
>     webfarm-50.q4web.com is a CNAME for ir.ssrmining.com

How so?

`dig CNAME +noadditional +noquestion +nocomments +nocmd +nostats webfarm-50.q4web.com. @1.1.1.1`

>webfarm-50.q4web.com.	60	IN	CNAME	webfarm-200.q4web.com.

**Comment by p1r473** [comment]
Possibly made a mistake here.
Will reopen if I can catch it again.
Thanks.

**Comment by n8v8R** [comment]
well that is a bit weird, you are actually correct  (sorry about that)


`
dig CNAME +noadditional +noquestion +nocomments +nocmd +nostats ir.ssrmining.com. @1.1.1.1`

>ir.ssrmining.com.	300	IN	CNAME	webfarm-50.q4web.com.

**Comment by n8v8R** [comment]
this seems resolved, the reported domain does not show in today's Basic | Ultimate sets
