### ISSUE TITLE
Question regarding blocklist filtering

### ISSUE THREAD

**Issue by mrclschstr** [EnergizedProtection/block#537]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [x] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: Basic

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: None

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
...
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: Pi-Hole

- Version: v5.1.2

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

Hi everyone,

first of all: Thanks for your great work!

Out of pure curiosity I digged into your code and wanted to explore how exactly you filter the block lists before merging them. I'll just pick the "WindowsSpyBlocker Hosts Spy" list as an example:

Original list: https://raw.githubusercontent.com/crazy-max/WindowsSpyBlocker/master/data/hosts/spy.txt

Your filtered version of this list: https://block.energized.pro/assets/sources/filter/windows-spy-blocker.txt

I think the filter magic happens in this snippet: https://github.com/EnergizedProtection/block/blob/2c3036f8b10e0d98a72a9b9b1de461ab9ddb3a99/assets/sources/filter.sh#L228-L241

There you are using the whitelist you pull from here: https://raw.githubusercontent.com/AdroitAdorKhan/Energized-Protection-Core/master/builds/whitelist.txt

Unfortunately I cannot access this list because of the missing token. Where does this whitelist come from? What are the criteria for a domain to get on this whitelist? I hope you can help me clarifying the filtering process.

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by AdroitAdorKhan** [comment]
Its a core repo, with a lot of core files. That is basically the main whitelist files merged with dead, inactive and false positive domains. You can use https://github.com/EnergizedProtection/unblock instead to filter the list.
