### ISSUE TITLE
us.dyn.indeed.com

### ISSUE THREAD

**Issue by p1r473** [EnergizedProtection/block#538]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name:  Ultimate, basic

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
us.dyn.indeed.com
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: PiHole

- Version: 5.0

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: us.dyn.indeed.com is neither malicious nor advertising. Also it is a CNAME for indeed.com

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by n8v8R** [comment]
> That means by blocking us.dyn.indeed.com, indeed.com is blocked if using some Deep CNAME Inspection blocking

This sound wrong and appears to a bug or misconfiguration in *Deep CNAME Inspection*. If properly configured the blockage of child subdomain should not block its parent (sub)domain.

I am utilising Ultimate and *indded.com* resolves just fine whilst *us.dyn.indeed.com* produces the expected NX

**Comment by p1r473** [comment]
> > That means by blocking us.dyn.indeed.com, indeed.com is blocked if using some Deep CNAME Inspection blocking
> 
> This sound wrong and appears to a bug or misconfiguration in _Deep CNAME Inspection_. If properly configured the blockage of child subdomain should not block its parent (sub)domain.
> 
> I am utilising Ultimate and _indded.com_ resolves just fine whilst _us.dyn.indeed.com_ produces the expected NX

This is the way Deep CNAME Inspection works, on purpose.
You must not be using Deep CNAME Inspection
![image](https://user-images.githubusercontent.com/9235633/90541588-e131ec00-e150-11ea-9f6f-6fdfe33da6e3.png)

**Comment by n8v8R** [comment]
> This is the way Deep CNAME Inspection works, on purpose. This is an extra security feature.

That clarifies for the OP that the issue is not valid here, and that was the point I was trying to make though without being familiar of *Deep CNAME Inspection*.

I just utilise RPZ with the local resolver instance and in that context the DNS path is not recursively walked up to parent domains.

**Comment by p1r473** [comment]
That is besides the point- us.dyn.indeed.com is not a malicious nor ad tracking domain and should be whitelisted.

**Comment by n8v8R** [comment]
Good that it has been clarified.

That PI-Hole however blocks the parent *indeed.com* must be something related to their feature, like said in RPZ context it works as expected.

**Comment by n8v8R** [comment]
It seems that *us.dyn.indeed.com*  acts as url forwarder to *indeed.com*

![Annotation 2020-08-18 193009](https://user-images.githubusercontent.com/13611490/90545688-4c97b000-e189-11ea-9de6-81328bcfa49a.png)

In that context it makes sense that PI-Hole blocks the connection but you should be able to access *indeed.com* directly from the browser URL bar.

**Comment by p1r473** [comment]
The problem is with the mobile app.
The Indeed mobile app displays a connection problem if this domain is blocked.
I have of course whitelisted the domain locally to allow full access- the purpose of this ticket is to try to remove the benign domain from the blocklist.
![image](https://user-images.githubusercontent.com/9235633/90546338-e7779680-e157-11ea-826d-af67f74995d9.png)

**Comment by DandelionSprout** [comment]
The entry appears to be sourced from *Airelle's Anti-Advertisements Hosts*, which makes it the 4th issue report I've looked through tonight where an Airelle list was to blame.

**Comment by p1r473** [comment]
I stopped using Airelle's list ages ago.
@AdroitAdorKhan consider removing this source as it is ill-maintained. Thanks!

**Comment by n8v8R** [comment]
this seems resolved, the reported domain does not show in current Basic | Ultimate sets
