### ISSUE TITLE
Blockade around a statistical institution of a government

### ISSUE THREAD

**Issue by boistordu** [EnergizedProtection/block#540]
Guys,

I'm a bit pissed off. So sorry in advance for that but do you realize that you have governmental statistics institution in your denylist ?
How do you make those list
Statbel.fgov.be is the federal institution of statistics in Belgium. 
It's not a fucking website of statistics for analytics in computer science or IT. 
We are talking about an respectful institution of a democracy in fucking Europe. How is that ending up in your list ? For real! You don't block statistics institution. You need them for any debate in any society at any time in human history. 
Thanks in advance

**Comment by n8v8R** [comment]
anyone forcing you to deploy these lists? Aside from your foul language you exhibiting an attitude of entitlement perhaps though without any contribution to the code.

Mistakes happens and aside from reporting an issue in a more civilized manner you could always elect to

* contribute to the code with a PR
* move on to another code that is more satisfactory

**Comment by boistordu** [comment]
And in place of getting an over-sized ego like nothing is your fault and that you are defending some editorial line or anything alike, maybe you could just acknowledge the mistake and be astonished that it have even been there. 

So maybe I used a foul language, but we are not talking about code here which could have been a complex line-up of functions or anything alike. 
No, we are talking about a list of domains or subdomains that should be tested and tested again before to be put in place. 
Because don't forget that those lists are being used also by "lambda" people that only use them through services like nextdns or alike. And this is put in place with the push of a button. 
I could easily feel the empathy(that apparently you lack) for those lambda people that would take hours if not days to understand where the problem comes from. 

I can easily understand that you are blocking every possible domain or nearly of Microsoft for example including the windowsupdate processes like I've seen today. So as you can see I'm always trying to be impartial and objective as the dev manager team that I am. But don't forget one thing, as you are exhibiting the repetitive behavior that I have been able to watch over the years about among dev and IT's:
The " do we force you to use our product... bla-bla-bla... " 
 So don't forget that, since you are trying to do an honorable thing with this list, it's often better to just acknowledge mistake when they are obvious like here in place of blaming the user who could be validly mad about something that obviously wrong.  Because what you  are doing there if I should do an analogy is a bit like the policeman that would say to the victim of a rape that she should'nt have put that short skirt, or in another matter, the government lying about the utility of the mask in time of pandemic just because they don't have them. Same principle ms, same dynamics of thought, just other subjects. Delegate the fault to others. 

Anyway don't worry next time I will do a change ´s request to the list in the code itself with the appropriate comments. 

Best regards
