### ISSUE TITLE
Domains misclassified as porn

### ISSUE THREAD

**Issue by OTechnician** [EnergizedProtection/block#552]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: 

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: porn

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
www.scielo.br
www.scn.org
www.science4all.org
www.scpr.org
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: 

- Version: 

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
Your porn blacklist contains sites that aren't related to porn content. Some of them are:

- SciELO.br is an online scientific electronic library
- Science4all is a webpage dedicated to science and education
- scn.org belongs to Seattle Community Network
- scpr.org belongs to Southern California Public Radio

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by DandelionSprout** [comment]
I have identified *Airelle's Anti-Sex Hosts* as the source where all 4 of those entries were fetched into Energized from.

Contacting him/her to remove those entries, seems to be a non-trivial problem. http://rlwpx.free.fr/WPFF/mel.htm links to an E-mail address that by their own admission isn't checked in detail, and a forum full of spambots.
