### ISSUE TITLE
manifest.prod.boltdns.net

### ISSUE THREAD

**Issue by p1r473** [EnergizedProtection/block#557]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name:  Ultimate

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
manifest.prod.boltdns.net
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: PiHole

- Version: 5.0

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
This domain is the manifest for boltDNS. Blocking this domain breaks embedded videos that use the BrightCove player. It is also a CNAME for dualstack.brightcove.map.fastly.net
 For example, try and play the embedded video on https://www.intel.ca/content/www/ca/en/products/docs/processors/core/performance-maximizer.html
This domain does not host any ads, spyware, or malware.

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by DandelionSprout** [comment]
It seems the entry [has been sourced from Energized's own *Core* development list](https://github.com/AdroitAdorKhan/EnergizedProtection/blob/master/core/hosts#L8568), which places the burden of adding a fix on the Energized team themselves.

**Comment by underhandedness** [comment]
This host is touched by some media streaming apps when some ad servers are blacklisted.  I have blocked it without loss of functionality.  The provided test URL in OP functions as expected.

Leave blocked.

**Comment by p1r473** [comment]
@underhandedness 
Did you try and visit the example I gave and see if you could play the video?
https://www.intel.ca/content/www/ca/en/products/docs/processors/core/performance-maximizer.html

**Comment by p1r473** [comment]
@underhandedness 
Did you actually try and play this video with the domain blocked?
Here's proof. Test it again- I did.

![image](https://user-images.githubusercontent.com/9235633/99814259-bd4ac180-2b16-11eb-98cd-356fefc05a1e.png)
