### ISSUE TITLE
app.energized.pro seems to be down

### ISSUE THREAD

**Issue by 4n0nymou2** [EnergizedProtection/block#559]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [x] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: 

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```

```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: 

- Version: 

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
I am using Fedora 32 and visited your website `app.energized.pro` via Brave browser but the page is not accessible.
It says "Your PHP installation appears to be missing the MySQL extension which is required by WordPress."
Please fix. Thank you

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by David-H-1** [comment]
Tested, the same problem happens when using Firefox browser and Chrome browser on Windows

**Comment by David-H-1** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/60801469/95693306-94164780-0be0-11eb-94e8-efa1844ac3ee.png)

**Comment by 4n0nymou2** [comment]
Now it's working. Closing.
