### ISSUE TITLE
Invalid hosts in list?

### ISSUE THREAD

**Issue by Ch4t4r** [EnergizedProtection/block#561]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [x] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: 

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: Ultimate

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
194.63.248.52\032quantadex.altcoincash.xyz
209.126.103.139\032cdn.adless.io
209.126.103.59\032cdn.adless.io
209.126.127.231\032cdn.adless.io
... And more
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: 

- Version: 

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
There are a lot of domains which I believe to be invalid. They contain slashes, followed by 032.<br>
All of them seem to come from `CoinBlockerLists`.<br><br>
Maybe `\u032` is meant, but as it is already broken in the source list that is only an assumption.
Or maybe `\032` serves as a divider between the IP-address part of the host and the domain?<br>
Either way, maybe Energized could remove those hosts, or only import the real domain part?

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by DandelionSprout** [comment]
This is a current known problem that is being worked on, but I can't give a time estimate for the fix because it depends on various changes being implemented in a backend that I lack proper access to: #562

**Comment by n8v8R** [comment]
Looking through the source code https://gitlab.com/search?utf8=✓&snippets=false&scope=&repository_ref=master&search=\032&project_id=6837855 it appears that `\032` pertains to cases with an IP and a domain name listed.

According to https://www.ascii-code.com the `/032` octet represents a control character described as _Substitute_ and which might be a bug at source, least judging from https://gitlab.com/ZeroDot1/CoinBlockerLists/-/issues/35

**Comment by n8v8R** [comment]
This issue probably can be closed after the next list compilation as the upstream source cleaned up https://gitlab.com/ZeroDot1/CoinBlockerLists/-/commit/ad48b6220f2ac8d943b677abbb8836b449cb8071?expanded=1

**Comment by Ch4t4r** [comment]
Agreed.
