### ISSUE TITLE
https://cronometer.com/#profile

### ISSUE THREAD

**Issue by Schanzation** [EnergizedProtection/block#59]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: Porn

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```

```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: uBlock Origin

- Version: 18.12.353

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

Hello! When I have enabled this filter in ublock origin- https://raw.githubusercontent.com/EnergizedProtection/block/master/porn/formats/hosts

I get this error:
https://imgur.com/a/sV8nmYo

When I disable this filter the error disappear. How can I fix this without disabling the filter? thnx

Here's the link:

https://cronometer.com/#profile

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

<p align="center"><a href="https://saythanks.io/to/AdroitAdorKhan" target="_blank"><img src="https://img.shields.io/badge/Say%20Thanks-!-1EAEDB.svg?longCache=true&style=flat-square"></a><p>

**Comment by AdroitAdorKhan** [comment]
Can you kindly check the uBlock Origin list, and which domain was blocked?

**Comment by Schanzation** [comment]
Domain is stripe.com

Maybe u need an account there to be able to replicate it

**Comment by AdroitAdorKhan** [comment]
Alright! I am whitelisting `stripe.com` only. If it still bothers, kindly check for any other sub domain and report back.

**Comment by AdroitAdorKhan** [comment]
Hope this was fixed!
