### ISSUE TITLE
Adding oisd.nl as an source

### ISSUE THREAD

**Issue by grubeli** [EnergizedProtection/block#618]
I'm using Energized Ultimate on AdGuard Home and works well!
The second blocklist source I'm using is [oisd.nl](https://oisd.nl/) [(adblock-format - normal)](https://abp.oisd.nl/), there are some not detected urls there, I think it would be good if you include the list as well in the current list, since oisd.nl is really good, clean, almost no FP blocklist

**Comment by underhandedness** [comment]
Seems like user could subscribe as you have.  Why merge?

**Comment by grubeli** [comment]
Same reason why /energized merges any other sources (see sources list), also osid.nl have a huge overlapping domains but still many unique ones

**Comment by yokoffing** [comment]
OSID is the gold standard for me. Love it. Huge number of lists but very few false positives. Both great community feedback and maintainer responses on the false positives that do slip through. A rare find!

Both Energized and OISD curate a blocklist from many sources, so just subscribe to both.

The creators of Energized are more than able to add sources that OISD uses that it lacks.

**Comment by DRSDavidSoft** [comment]
Personally, I use OISD + Energized (with some other blacklists, such as 1Hosts) all together.  Even though they cover mostly the same domains, there are some that only exist in one of the aggregated lists, and not the other.

**Comment by AdroitAdorKhan** [comment]
OISD Basic list has been added.

**Comment by angelss197200** [comment]
@AdroitAdorKhan
why not the full version?
