### ISSUE TITLE
Request for block: tct-teye.com [Android App]

### ISSUE THREAD

**Issue by DRSDavidSoft** [EnergizedProtection/block#625]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [x] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [x] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: Energized Blu

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
www.tct-teye.com
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: DNSCrypt-proxy + Pihole + Unbound

- Version: 20.11.330.12

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

After installing a **[Gallery app](https://play.google.com/store/apps/details?id=com.tclhz.gallery&hl=en_US&gl=US)** from the Developer **[Cloud Innovation Studio](https://play.google.com/store/apps/developer?id=Cloud+Innovation+Studio)** on a secondary Android device, I noticed that it started to communicate with the domain: ```www.tct-teye.com```

Here's a dump of requests that were made to this domain:

- `GET https://www.tct-teye.com/get-config/?configurationName=datahub&version=-1&appName=com.tclhz.gallery`  
    ```json
    {"datahub":"on","max_mobile_events_un_upload":100,"max_failed_times":50,"schedule_interval_second":"86400","upload_policy_flag":47,"upload_control_req_flag":7,"counts_policy_schedule_interval_hours":24,"request_service_config_interval_hours":"24","switch_off_versions":["2.00.14"],"switch_off_countries":["250","310","311","312","313","314","315","316","330","332","534","535","544","208","308","340","543","546","547","647","742","204","362","363","238","288","290","235","266","346","348","350","354","376","750","262","222","206","270","272","202","214","268","232","244","240","260","230","216","231","293","280","278","247","246","248","284","226","219"]}
    ```

- `POST https://www.tct-teye.com/collection/mobile-data/dailyData/`  
    ```Content-Disposition: form-data; name="phoneData"; filename="comp_data.zip"```
    ```json
    {"msg":"success","data":"save file success","code":200}
    ```

Here's the scary part: the `comp_data.zip` file that is being uploaded as `phoneData`, is a ZIP file that includes the following JSON data:

```json
{
    "timeZone": "GMT+xx:xx",
    "baseInfo": {
        "teyeId": "xxxxxxxxxxx",
        "deviceName": "xxxxxx",
        "model": "xxxxxxx",
        "countryNo": "xx",
        "androidVersion": "x.x.x",
        "romVersion": "xxxxxxx_xxxxxx-xxxxxxxxx x.x.x XXXXXX xxxxxxxxxx xxxx-xxxx",
        "timeZone": "GMT+xx:xx",
        "mcc": "xxx",
        "appName": "Gallery",
        "appVersion": "v8.3.0.0.G078.0",
        "appInstallTime": 1599965043887,
        "appLastUpdateTime": 1599965043887,
        "appInstallSource": "com.android.packageinstaller",
        "packageName": "com.tclhz.gallery"
    },
    "eventList": [{
        "_id": 62,
        "happenTime": "1605291103280",
        "packageName": "com.tclhz.gallery",
        "teyeId": "xxxxxxxxxxx",
        "appVersion": "v8.3.0.0.G078.0",
        "activityName": "com.tcl.gallery.app.GalleryActivity",
        "actionName": "ActivitySession",
        "duration": "8820"
    }]
}
```

I have redacted the fields that reveal my secondary device.  It seems that `teyeId` is a uniquely generated identifier that tracks the installation, as well as information regarding the device.

Based on [this repo](https://github.com/yifan-Eric/teye-dist/blob/master/src/js/config/api.js) ([backup](https://web.archive.org/web/20201125114327if_/https://raw.githubusercontent.com/yifan-Eric/teye-dist/master/src/js/config/api.js)), I can some other endpoints / package names as well that might be affected:

```javascript
const loginUrl = 'https://www.test-teye.com/chaos/login.html';

const apiTest = [
    '/getAllData',
    '/postPerfData',
    '/report/com.tct.camera/getAppPMActiveInfo',
    '/report/retention',
    '/report/hotevent',
    '/report/com.tct.camera/appUserActiveInfo',
    '/report/getAppDistribution',
    '/report/getDeviceNumber',
    '/report/getAndroidVersion',
    '/report/com.tclhz.gallery/getAppVersionList',
    '/report/device-report/getDeviceActiveOfDay',
    '/report/userEngagement',
    '/report/index/getPainSpotList',
    '/report/getAppList',
    '/report/getActivityCount?packageName=flink-com.tclhz.gallery',
    '/report/app/version/list'
];
```

Their base of operation seems to be located in China, and this tracking endpoint is being used to collect bid gata on mobile devices.

I have tested the app and can confirm that they work fine with this domain being blocked (in fact they start faster). As this domain is not blocked in other domain blacklists (including Energized), I'd like to ask for it to be blacklisted, in order to avoid the tracking by said apps.

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by DRSDavidSoft** [comment]
@AdroitAdorKhan Closed without being added?

**Comment by AdroitAdorKhan** [comment]
@DRSDavidSoft Have you updated your blocklist yet? 

I guess, you haven't! 

![image](https://user-images.githubusercontent.com/9679103/112594398-10b97d00-8e33-11eb-8d4b-6c517ed3a70f.png)
![image](https://user-images.githubusercontent.com/9679103/112594481-38a8e080-8e33-11eb-8a25-66466c82b1bc.png)
![image](https://user-images.githubusercontent.com/9679103/112594510-49f1ed00-8e33-11eb-8700-c02c6806040d.png)
![image](https://user-images.githubusercontent.com/9679103/112594566-58d89f80-8e33-11eb-9b8c-e72dc983e71b.png)

**Comment by DRSDavidSoft** [comment]
Thanks, @AdroitAdorKhan! I checked beforehand of course, I guess the update wasn't applied.  Sorry to bother you!

**Comment by AdroitAdorKhan** [comment]
@DRSDavidSoft no problem mate!
