### ISSUE TITLE
filters.adtidy.org should not be blocked

### ISSUE THREAD

**Issue by cbwee** [EnergizedProtection/block#681]
filters.adtidy.org is the domain for updating AdGuard filters, and it should not be blocked, please remove it, I was using Energized Spark.

**Comment by aravindvnair99** [comment]
It's being blocked in the unified list as well. This shouldn't be blocked as mentioned by @CB-wee.

**Comment by eric15342335** [comment]
same here, wondering why it has been added into the block lists

**Comment by aravindvnair99** [comment]
> same here, wondering why it has been added into the block lists

@eric15342335 It's no longer blocked when I checked right now on my Pi-hole.

**Comment by cbwee** [comment]
I just checked again, it is still blocked in Energized Spark.

https://block.energized.pro/spark/formats/hosts.txt
