### ISSUE TITLE
userlocation.googleapis.com shouldn't be blocked

### ISSUE THREAD

**Issue by aravindvnair99** [EnergizedProtection/block#685]
### Pack Name: Unified

<hr>

### Domain(s):

```
userlocation.googleapis.com
```

<hr>

### Your Config:

- Client: Pi-hole
- Version: 21.02.040

<hr>

### Details:

I don't see any reason for it to be blocked.

**Comment by aravindvnair99** [comment]
Fixed.

**Comment by thatcatdrout** [comment]
this is the exact domain google uses to location track people
