### ISSUE TITLE
Please allow host list download over http

### ISSUE THREAD

**Issue by AnielShri** [EnergizedProtection/block#698]
### Issue(s):
- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [x] Request
- [ ] Other Issue

### Your Config:

* Router: TP-Link TL-WR841ND v10
* Software: DD-WRT v3.0-r45767 
* Script: https://github.com/AnielShri/ddwrt-adblocker

### Details:
I'm running a script on my router that creates a blacklist based on a hostfile. This file is automatically downloaded/updated every week. I'm currently using  [Steven Black's](https://github.com/StevenBlack/hosts) host file: `http://sbc.io/hosts/hosts`.

Because his hostfile is based on individual domains, subdomains don't always get blocked. I want to implement the blacklist using `dsnmasq` for a better solution and `Blu GO` seems like the perfect candidate for that. The problem is that your site redirect **`http`** traffic to the **`https`** url. While I understand that this might be for security reasons, the limited version of `wget` (busybox) on my router is unable to handle https urls. 

So my request: `can you make it so that host files are downloadable over http`?

___

#### The current response from your server over `http`:
```
Request URL: http://block.energized.pro/spark/formats/dnsmasq.conf
Request Method: GET
Status Code: 301 Moved Permanently
Remote Address: 136.243.241.83:80
Referrer Policy: no-referrer-when-downgrade
Connection: keep-alive
Content-Length: 194
Content-Type: text/html
Date: Sat, 27 Feb 2021 21:22:32 GMT
Location: https://block.energized.pro/spark/formats/dnsmasq.conf
Server: nginx/1.14.0 (Ubuntu)
```

**Comment by AvinashReddy3108** [comment]
Tagging @AdroitAdorKhan coz he handles the server stuff.

**Comment by aravindvnair99** [comment]
>  While I understand that this might be for security reasons

@AnielShri as you mentioned yourself...

It makes no sense to disallow HTTP to HTTPS redirection. Why not get the file and host it somewhere else on your own on HTTP so that your router is able to download it?

**Comment by ignoramous** [comment]
I wonder if downloading over http makes sense without something to determine downloaded hostfile's integrity.

Better off downloading it via https and hosting it on machines on LAN for `wget` to get that from there, instead.

**Comment by AnielShri** [comment]
Thanks all for the replies, I'll find another workaround.
