### ISSUE TITLE
Torproject and others blocked 

### ISSUE THREAD

**Issue by colbycdev** [EnergizedProtection/block#70]
[x] whitelist
Pack version: no clue, using Blokada which downloads every day
Packs used: blu, extreme, regional, social
The domain metrics.torproject.org is blocked. This is ridiculous, its the Tor Project
Also, www.reddit.com is blocked (not sure that's bad, though😉)

**Comment by fmilligan** [comment]
@colbycdev Of all things to block, torproject?

**Comment by Atavic** [comment]
Most probably bundled as any *metrics.* address.

**Comment by AdroitAdorKhan** [comment]
Reddit is blocked in Social List. Torproject Domains will be fixed.
