### ISSUE TITLE
[False Positive] code.visualstudio.com

### ISSUE THREAD

**Issue by grubeli** [EnergizedProtection/block#721]
I think blocking with IP is very false positive prone, since many different domains can be hosted on a same IP.
For example, `code.visualstudio.com`  which I assume almost all developers use is blocked

![image](https://user-images.githubusercontent.com/74614193/113509376-1dce1e80-954d-11eb-8f8d-1672ec4a8848.png)

**Comment by AdroitAdorKhan** [comment]
`code.visualstudio.com` is not blacklisted in any of our lists. As this is from CNAME, `trafficmanager.net` could be the reason.

**Comment by grubeli** [comment]
Thanks Ador,
I guess whitelisting the domain is only option for now
