### ISSUE TITLE
new list -> blocklists-unit42-silverterrier

### ISSUE THREAD

**Issue by scafroglia93** [EnergizedProtection/block#762]
based on panunit42 silverterrier (nigerian emal scam)

Source ->
https://raw.githubusercontent.com/scafroglia93/blocklists/master/blocklists-unit42-silverterrier.txt

**Comment by T145** [comment]
I've actually been researching some of these sources: https://github.com/T145/the-blacklist/issues/22

Can you give some more details on them? I'm interested in hearing some of your research, as https://github.com/pan-unit42/iocs is a bit daunting at first glance.
