### ISSUE TITLE
block.energized.pro dead?

### ISSUE THREAD

**Issue by Oshawott-kun** [EnergizedProtection/block#775]
anyone block.energized.pro is dead?
i got error this
--2021-07-18 21:37:38--  https://block.energized.pro/bluGo/formats/hosts.gz
Resolving block.energized.pro (block.energized.pro)... 136.243.241.83
Connecting to block.energized.pro (block.energized.pro)|136.243.241.83|:443... failed: No route to host.

how i fix it?

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [x] Website Broken
- [ ] Request
- [ ] Other Issue

**Comment by theintel** [comment]
Experiencing the same issue while trying to update. It was working fine till now. It got rid of the working one before updating but failed to update. Now I can't even revert back to previous filters.

**Comment by gallegonovato** [comment]
Good afternoon: they still do not go. And before they had a gitlab but it doesn't allow to enter either. Do you know if they will go again? A hug

**Comment by SaberAkiyama** [comment]
Duplicate from #768

**Comment by ndr48291** [comment]
@AdroitAdorKhan

**Comment by theintel** [comment]
As the site is down, can someone please share the raw hosts for Spark package? (if you have a local copy of the hosts)

**Comment by ben-dd** [comment]
> As the site is down, can someone please share the raw hosts for Spark package? (if you have a local copy of the hosts)

Ill second that for all the lists if anyone has them.

**Comment by Oshawott-kun** [comment]
> As the site is down, can someone please share the raw hosts for Spark package? (if you have a local copy of the hosts)

Yeah can share Unlimited pack too

**Comment by zQueal** [comment]
[basic.txt](https://github.com/EnergizedProtection/block/files/6921308/basic.txt)
[blu.txt](https://github.com/EnergizedProtection/block/files/6921309/blu.txt)
[bluGo.txt](https://github.com/EnergizedProtection/block/files/6921310/bluGo.txt)
[spark.txt](https://github.com/EnergizedProtection/block/files/6921313/spark.txt)
[ultimate.txt](https://github.com/EnergizedProtection/block/files/6921314/ultimate.txt)
[unified.txt](https://github.com/EnergizedProtection/block/files/6921315/unified.txt)
[ips.txt](https://github.com/EnergizedProtection/block/files/6921311/ips.txt)
[social.txt](https://github.com/EnergizedProtection/block/files/6921312/social.txt)
[xtreme.txt](https://github.com/EnergizedProtection/block/files/6921316/xtreme.txt)


Just compiled these because I noticed the site was down.

**Comment by theintel** [comment]
@zQueal Thanks a lot! You're a lifesaver.

**Comment by Oshawott-kun** [comment]
> [basic.txt](https://github.com/EnergizedProtection/block/files/6921308/basic.txt)
> [blu.txt](https://github.com/EnergizedProtection/block/files/6921309/blu.txt)
> [bluGo.txt](https://github.com/EnergizedProtection/block/files/6921310/bluGo.txt)
> [spark.txt](https://github.com/EnergizedProtection/block/files/6921313/spark.txt)
> [ultimate.txt](https://github.com/EnergizedProtection/block/files/6921314/ultimate.txt)
> [unified.txt](https://github.com/EnergizedProtection/block/files/6921315/unified.txt)
> [ips.txt](https://github.com/EnergizedProtection/block/files/6921311/ips.txt)
> [social.txt](https://github.com/EnergizedProtection/block/files/6921312/social.txt)
> [xtreme.txt](https://github.com/EnergizedProtection/block/files/6921316/xtreme.txt)
> 
> Just compiled these because I noticed the site was down.

Thanks man

**Comment by Oshawott-kun** [comment]
Ok man if you want Hosts raw you cant download on wayback machine

https://web.archive.org/web/20210414150549/https://block.energized.pro/


I still open this issue because the server still broken

**Comment by patcheco1001** [comment]
> 
> 
> [basic.txt](https://github.com/EnergizedProtection/block/files/6921308/basic.txt)
> [blu.txt](https://github.com/EnergizedProtection/block/files/6921309/blu.txt)
> [bluGo.txt](https://github.com/EnergizedProtection/block/files/6921310/bluGo.txt)
> [spark.txt](https://github.com/EnergizedProtection/block/files/6921313/spark.txt)
> [ultimate.txt](https://github.com/EnergizedProtection/block/files/6921314/ultimate.txt)
> [unified.txt](https://github.com/EnergizedProtection/block/files/6921315/unified.txt)
> [ips.txt](https://github.com/EnergizedProtection/block/files/6921311/ips.txt)
> [social.txt](https://github.com/EnergizedProtection/block/files/6921312/social.txt)
> [xtreme.txt](https://github.com/EnergizedProtection/block/files/6921316/xtreme.txt)
> 
> Just compiled these because I noticed the site was down.

Thanks @zQueal for your workaround but Pi-hole found only 23022 domains in the Unified version. It's abnormal.
Are you sure the compilation has successed ?

**Comment by ben-dd** [comment]
> Thanks @zQueal for your workaround but Pi-hole found only 23022 domains in the Unified version. It's abnormal.
> Are you sure the compilation has successed ?

Same issue for me, Unified usually has well over 1 million domains doesn't it?

**Comment by theintel** [comment]
> Ok man if you want Hosts raw you can download on wayback machine
> 
> https://web.archive.org/web/20210414150549/https://block.energized.pro/
> 
> I still open this issue because the server still broken

Despite file downloading taking unusually long time, I was able to download raw hosts for Spark. Thank you for sharing the archived version.

**Comment by zQueal** [comment]
Doesn't seem like this is going to work at all....

Looks like the build scripts aren't really setup correctly (not sure how I missed the errors) and without the methodology into how they're supposed to work, it's kind of hard to fix them.

Using archive.org isn't working either. The ultimate pack, which is supposed to contain 1.38 million records only contains about 33.3k. Without Ador rewriting the build scripts to have some form of continuity, it's just probably not going to work.

**Comment by patcheco1001** [comment]
I found some recent versions (dated last month) hosted on the blokada's mirror:
| Pack  | Entries |  Download |
| ------------- | ------------- | ------------- |
| Basic  | 402,371  | [hosts.txt](https://blokada.org/mirror/v5/energized/basic/hosts.txt)
| Blu  | 233,167  | [hosts.txt](https://blokada.org/mirror/v5/energized/blu/hosts.txt)
| Spark | 41,897  | [hosts.txt](https://blokada.org/mirror/v5/energized/spark/hosts.txt)
| Ultimate | 1,039,428  | [hosts.txt](https://blokada.org/mirror/v5/energized/ultimate/hosts.txt)

**Comment by ch3mn3y** [comment]
Thanks to all this hosts but they don't seem to work for me. AdAway sees the file, but doesn't add anything to hosts...
Ehh, and I thought i broke something when ads started to show line a week ago...

**Comment by zQueal** [comment]
Working fine for me with AdAway. Not sure what you're doing wrong.

**Comment by ch3mn3y** [comment]
Im just adding the txt hosts file, applying it and after some times added hosts are "up to date", but added entry doesn't show any new blocked sites...
Will try other files. Tried only Ultimate/Unified as that was what I used before. Even less is more :)

**Comment by theintel** [comment]
@patcheco1001 That's great. Will try these out too. Thanks!

**Comment by unknown4849** [comment]
@zQueal you can use mirror rename to 280blocker

**Comment by RaptorSDS** [comment]
@zQueal thanks for work but all of your files i got win32.Trojan Fonix-cc warning from my AVG suite 

@patcheco1001  your files work fine with pihole and AVG

**Comment by zQueal** [comment]
> thanks for work but all of your files i got win32.Trojan Fonix-cc warning from my AVG suite

Probably because AVG is picking up the URLs within the file via heuristic analysis.

**Comment by bntsp** [comment]
The scripts are mostly up and running here. I spend some time searching for the lists downloaded from https://block.energized.pro/mirror/...    I found approx. 75 % on different sources.  Many of them are from sources that are dead for years already. It's a guess, but I think that most of the domains are already integrated into other lists.

When I have everything stable, I will start uploading.

**Comment by eric15342335** [comment]
[energized.pro](https://energized.pro) is back guys

**Comment by Oshawott-kun** [comment]
> [energized.pro](https://energized.pro) is back guys

Yooo that great
I will close this issue now

**Comment by Oshawott-kun** [comment]
On module magisk is work too so i officially close this issue

Thanks everyone for help me

**Comment by gyCfjSnO** [comment]
Can anyone explain what happened and why the blocklists all disappeared from GitHub
