### ISSUE TITLE
No updates since 2019-01-01 : Energized still alive?

### ISSUE THREAD

**Issue by StanGets** [EnergizedProtection/block#78]
Hi,

None of Energized' lists has been updated since January 1st, 24 days ago, whilst the sources, or at least some of them, have been updated.

May I still rely on Energizedprotection? If you've abandoned the project please say so because those of us who use your lists rely on those, because protection is not a lottery.

Thanks.

**Comment by k4rn8g3** [comment]
@StanGets we understand your concern, but rest assured that EnergizedProtection isnt dead and we will update it soon with all the source updates and user requested blacklist/whitelist.

**Comment by terrorist96** [comment]
The website should be updated.
![img_20190125_163948_684](https://user-images.githubusercontent.com/12802056/51774325-de2f6080-20bf-11e9-9c09-0449a92dfa56.jpg)

**Comment by AdroitAdorKhan** [comment]
Apologize for any inconvenience caused by my late arrival! I had some personal stuffs to deal with.
And most importantly Energized isn't dead yet! 

@StanGets yea! Had some important stuffs going on! @terrorist96 I am back! ;)

**Comment by terrorist96** [comment]
And he's gone again. 🤨

**Comment by AdroitAdorKhan** [comment]
Still Alive and Rocking! ;)
