### ISSUE TITLE
Source/scripts complete?

### ISSUE THREAD

**Issue by bntsp** [EnergizedProtection/block#781]
Hi,

does anybody know if the scripts in the source are complete and will work out of the box?
Then I can setup everything and put the lists to github.

btw: are there any issues with using the lists (license etc.) ? 

Thanks
Marcus

**Comment by AvinashReddy3108** [comment]
- The scripts are complete
- You may not be able to build hosts OOTB as it may need the whitelist file (which is in a private repo)

**Comment by bntsp** [comment]
**Short update:**

- Mostly working by now. Still trying to find copies of all the lists that are dead because they reside on block.energized.pro.
- Anybody out here with a copy?

  {"name": "280blocker",                         "enabled": true,    "filter": "active",    "format": "adblock",  "url": "https://block.energized.pro/mirror/280blocker_domain_ag.txt"},
  {"name": "airelle-pub",                        "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/airelle-pub.txt"},
  {"name": "airelle-rsk",                        "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/airelle-rsk.txt"},
  {"name": "airelle-sex",                        "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/airelle-sex.txt"},
  {"name": "airelle-trc",                        "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/airelle-trc.txt"},
  {"name": "hosts-file.net-ats",                 "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/hosts-file.net-ats.txt"},
  {"name": "hosts-file.net-emd",                 "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/hosts-file.net-emd.txt"},
  {"name": "hosts-file.net-exp",                 "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/hosts-file.net-exp.txt"},
  {"name": "hosts-file.net-fsa",                 "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/hosts-file.net-fsa.txt"},
  {"name": "hosts-file.net-grm",                 "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/hosts-file.net-grm.txt"},
  {"name": "hosts-file.net-hfs",                 "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/hosts-file.net-hfs.txt"},
  {"name": "hosts-file.net-hjk",                 "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/hosts-file.net-hjk.txt"},
  {"name": "hosts-file.net-main",                "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/hosts-file.net-main.txt"},
  {"name": "hosts-file.net-mmt",                 "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/hosts-file.net-mmt.txt"},
  {"name": "hosts-file.net-pha",                 "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/hosts-file.net-pha.txt"},
  {"name": "hosts-file.net-psh",                 "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/hosts-file.net-psh.txt"},
  {"name": "hosts-file.net-wrz",                 "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/hosts-file.net-wrz.txt"},
  {"name": "mailborder-phishing-bad-sites",      "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/mailborder.txt"},
  {"name": "mobile-ad-trackers",                 "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/assets/sources/filter/mobile-ad-trackers.txt"},
  {"name": "prigent-ads",                        "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/ut1-publicite.txt"},
  {"name": "prigent-adult",                      "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/ut1-adult.txt"},
  {"name": "prigent-cryptojacking",              "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/ut1-cryptojacking.txt"},
  {"name": "prigent-gambling",                   "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/ut1-gambling.txt"},
  {"name": "prigent-malware",                    "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/ut1-phishing.txt"},
  {"name": "prigent-phishing",                   "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/ut1-phishing.txt"},
  {"name": "zeustracker.abuse.ch",               "enabled": true,    "filter": "active",    "format": "plain",    "url": "https://block.energized.pro/mirror/zeustracker.abuse.ch.txt"}

**Comment by bntsp** [comment]
back online. not needed any more
