### ISSUE TITLE
False positive - shortpixel.ai

### ISSUE THREAD

**Issue by pdobrescu** [EnergizedProtection/block#787]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: Energized

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s): 

```
shortpixel.ai
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: 

- Version: 

<hr>

### Detail:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
Hello, 

ShortPixel is an [image optimization service](https://shortpixel.com) used by tens of thousands of websites and has nothing to do with ads, malware or other types of reasons why domains are present on your lists. The domain `cdn.shortpixel.ai` is used to serve optimized images for the sites through our [WordPress plugin](https://wordpress.org/plugins/shortpixel-adaptive-images/) and we do our best to block any site that misuses our services. However that's not always possible as you already know. 

Therefore, I'm kindly asking you to tell us what do we need to do to be removed from your list and I assure you of our full cooperation. We don't know the reasons why we have been added on this list and we'll do our best to fix whatever issue has caused our domain to be listed here. 

Thank you!

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by AdroitAdorKhan** [comment]
Thanks for reaching us out. Will be fixed with the next update.

**Comment by pdobrescu** [comment]
Many thanks for the quick response @AdroitAdorKhan
