### ISSUE TITLE
hn.algolia.com: False positive

### ISSUE THREAD

**Issue by m3adow** [EnergizedProtection/block#8]
`https://hn.algolia.com` is a popular search site for Hacker news (https://news.ycombinator.com/) including an API. Blocking this host breaks functionality for at least one Hacker News App (Materialistic).

**Comment by k4rn8g3** [comment]
@m3adow Submit to app.energized.pro
And we'll see what we can do..

**Comment by m3adow** [comment]
Done. I assume this can be **closed** then.
