### ISSUE TITLE
Unable to download packs with the HostsMan application

### ISSUE THREAD

**Issue by ghost** [EnergizedProtection/block#81]
Hi,

Happy to see that _EnergizedProtection_ packs are again updated.

I have a concern related to downloading whatever _EnergizedProtection_ pack with the _Hostsman_ application.

The Readme.md / Best Use states:

> windows: On Windows, you can use HostsMan to get the best Windows Hosts Usage Experience.

Problem is, whatever applicable download source (_HOSTS TXT_ or _HOSTS MIRROR_) _HostsMan_ won't download the pack.

For the BLU package, i.e. we have:

HOSTS TXT : https://raw.githubusercontent.com/EnergizedProtection/block/master/blu/formats/hosts.txt
HOSTS MIRROR : https://energized.pro/blu

**Hostsman has never been able to download sources from GitHub, this is not new, but not being able to download from a mirror is surprising, and i believe it's caused by the download format https://energized.pro/blu because Hostsman needs a file, explicitly.**

Hostsman's version is 4.8.106 (latest and last I think because the Hostsman project seems to have been abandoned). Screenshots:

1- Asking Hostsman to test https://raw.githubusercontent.com/EnergizedProtection/block/master/blu/formats/hosts.txt

![blu-1](https://user-images.githubusercontent.com/42912760/52163309-8789de00-26e0-11e9-9d8b-a5c84c19f5cb.jpg)

2- Asking HostsMan to test https://energized.pro/blu

![blu-2](https://user-images.githubusercontent.com/42912760/52163319-9ec8cb80-26e0-11e9-869f-b91d79441b44.jpg)

As a workaround I download the BLU package separately and then tell Hostsman to load a local source, that of the downloaded BLU pack. But having HostsMan download directly would be nicer!

Thanks for your work and commitment to a better web :=)

**Comment by AdroitAdorKhan** [comment]
It's Hostsman's issue. And, we couldn't provide mirror service either, because of the ever growing user base and running out of limited bandwidth. So, you may need to do it manually!
