### ISSUE TITLE
grnh.se

### ISSUE THREAD

**Issue by p1r473** [EnergizedProtection/block#814]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name:  Ultimate basic

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
grnh.se
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: PiHole

- Version: 5.0

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
grnh.se is a URL shortener service for greenhouse.io
Based on you not blocking some other URL shortening services, as well as not blocking greenhouse.io, I was wondering if this may have been a false positive
Though I do agree that some URL shortening services may havesome level of click tracking.

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by AdroitAdorKhan** [comment]
@p1r473 this doesn't seem right! we are not using any of Airelle's lists in our regular packs. Only his Porn list in Porn pack. Also, the domain you mentioned, is currently not blocked in any of our lists. Which source are you using? and can you check you are using official EPRO pack from original source? 
![image](https://user-images.githubusercontent.com/9679103/137380105-2e8c6961-81e2-4717-8c35-fb342e4c37d8.png)

**Comment by p1r473** [comment]
Sorry, seems to be a manual error on my part. Will reopen if I can replicate.
