### ISSUE TITLE
[request] directory website from trustpositif.kominfo.go.id

### ISSUE THREAD

**Issue by 3xploiton3** [EnergizedProtection/block#82]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following infos properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [ ] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ x] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: ultimate

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: xtreme + regional

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s): 

```
https://trustpositif.kominfo.go.id/downloaddb.php
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: ublock origin

- Version: latest

<hr>

### Details:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
add to blacklist energized
this host contain: gambling + porn + phising + etc
https://trustpositif.kominfo.go.id/downloaddb.php

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great with your kind help!</h2>
</div>

<p align="center"><sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<p>

<p align="center"><a href="https://saythanks.io/to/AdroitAdorKhan" target="_blank"><img src="https://img.shields.io/badge/Say%20Thanks-!-1EAEDB.svg?longCache=true&style=flat-square"></a><p>

**Comment by 3xploiton3** [comment]
link is dead

**Comment by 3xploiton3** [comment]
New Address

https://trustpositif.kominfo.go.id/files/downloads/database/blacklist/pengaduan/domains

**Comment by 3xploiton3** [comment]
Pornography 773517
Radicalism 199
SARA 163
Child Pornography 3
Fraud 1691
Gambling 4655
Security 10
Copyright 348

**Comment by AdroitAdorKhan** [comment]
Won't be a good idea to add! So closing here.
