### ISSUE TITLE
simplelogin.co

### ISSUE THREAD

**Issue by bbhtt** [EnergizedProtection/block#931]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Energized Ultimate

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: N/A

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

```
simplelogin.co
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: NextDNS

- Version: N/A

<hr>

### Detail:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 

`simplelogin.co` is another address used by https://simplelogin.io/, the mail aliasing service owned by Proton.

```
% This is the RIPE Database query service.
% The objects are in RPSL format.
%
% The RIPE Database is subject to Terms and Conditions.
% See http://www.ripe.net/db/support/db-terms-conditions.pdf

% Note: this output has been filtered.
%       To receive output for a database update, use the "-B" flag.

% Information related to '176.119.200.0 - 176.119.200.255'

% Abuse contact for '176.119.200.0 - 176.119.200.255' is 'abuse@protonmail.ch'

inetnum:        176.119.200.0 - 176.119.200.255
netname:        CH-PROTONDRIVE-20200106
country:        DE
org:            ORG-PTA32-RIPE
admin-c:        SC22600-RIPE
tech-c:         SC22600-RIPE
status:         ALLOCATED PA
mnt-by:         RIPE-NCC-HM-MNT
mnt-by:         protonmail-mnt
created:        2020-01-06T12:38:11Z
last-modified:  2021-11-08T16:10:31Z
source:         RIPE

organisation:   ORG-PTA32-RIPE
org-name:       Proton AG
country:        CH
org-type:       LIR
address:        Route de la Galaise 32
address:        1228
address:        Plan-les-Ouates
address:        SWITZERLAND
phone:          +41 22 548 35 51
admin-c:        SC22600-RIPE
tech-c:         SC22600-RIPE
abuse-c:        AR57305-RIPE
mnt-by:         RIPE-NCC-HM-MNT
mnt-by:         protonmail-mnt
created:        2019-12-30T09:09:22Z
last-modified:  2021-11-29T11:32:37Z
source:         RIPE # Filtered
mnt-ref:        protonmail-mnt

role:           Sebastien Ceuterickx
address:        Chemin du Pré-Fleuri, 3
address:        1228
address:        Plan-les-Ouates
address:        SWITZERLAND
phone:          +41 22 548 35 51
nic-hdl:        SC22600-RIPE
mnt-by:         mnt-ch-protondrive-1
created:        2019-12-30T09:09:21Z
last-modified:  2019-12-30T09:09:22Z
source:         RIPE # Filtered

% Information related to '176.119.200.0/24AS62371'

route:          176.119.200.0/24
origin:         AS62371
mnt-by:         protonmail-mnt
created:        2020-01-31T14:00:59Z
last-modified:  2021-12-03T12:01:03Z
source:         RIPE
```

That domain is used as a kind of redirect I think when loading https://app.simplelogin.io/auth/login in a mobile browser. Blocking that prevents https://app.simplelogin.io/auth/login from displaying.

![image](https://user-images.githubusercontent.com/62639087/184265214-983fc907-45c4-49c0-a769-0bb88dfd64e1.png)

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by bbhtt** [comment]
This is coming from this source: https://github.com/EnergizedProtection/block/blob/9505cadca6d17a10f64b4df4f01a20da038aa70b/assets/sources/sources.json#L629

Unfortunately I don't see a way to ask them to remove it https://www.stopforumspam.com/removal, it says my IP and my email address is not in their blocklist, so seems they only accept request from domain owners.

**Comment by bbhtt** [comment]
Duplicate https://github.com/EnergizedProtection/block/issues/907

**Comment by macbugs** [comment]
> `https://stopforumspam.com/downloads/toxic_domains_whole.txt`

--This is the list that accidentally [blocked most of Australia](https://www.stopforumspam.com/forum/viewtopic.php?id=9146) last year.

I tried to join the support forum and the server replies:

> _"Account details blacklisted. Your details have been found in our database and thus are not allowed to register. This incident has been reported."_

I dont even know what that means: I have never used the forum before and they do not explain the "violation".  It seems like nothing can be accomplished there, and this source should be filtered or removed:

That list is intended **_ONLY_** for the owners of web forums who need to prevent forum spam [incoming traffic] and should _not_ be used as an application firewall (to filter outgoing traffic.)

> *sniffs*
> [_...i think theres someone using SFS as firewall._](https://www.stopforumspam.com/forum/viewtopic.php?pid=51803#p51803)
> *grabs pitchfork*
