### ISSUE TITLE
energized.pro website down

### ISSUE THREAD

**Issue by hunterzero99** [EnergizedProtection/block#945]
The energized.pro website seems to be down.  I receive the below error message when trying to load the site.  I have tried from a wired internet connection as well as two different cell providers I have access to.
Same error comes down when trying to download a blocklist from the website energized.pro

Error. Page cannot be displayed. Please contact your service provider for more details. (19)

**Comment by freMea** [comment]
I confirm.

**Comment by zQueal** [comment]
Confirmed. Magisk module automatically removed hosts file while updating... No longer protected.

**Comment by hunterzero99** [comment]
Seems to be back up now, thank you!
