### ISSUE TITLE
Unblock mstdn.io, nextdns.io

### ISSUE THREAD

**Issue by teakoder** [EnergizedProtection/block#972]
### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: Ultimate

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
mstdn.io

nextdns.io
api.nextdns.io
favicons.nextdns.io
dns1.nextdns.io
my.nextdns.io
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: NextDNS

- Version: Latest

<hr>

### Detail:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.
- Your Issue Detail: mstdn.io domain (a Mastodon server) was working well since 2017. I don't know why it was blocked today. I'm using NextDNS as my blocklists manager. However, I am unable to access NextDNS to manually whitelist these domains.

**Comment by correabuscar** [comment]
Why not `*.nextdns.io` ?
At least this one needs to be added also: `link-ip.nextdns.io`

**Comment by teakoder** [comment]
@correabuscar I think it's good to be accurate when reporting issue. Trying to make the project's maintainers life easier.
As for `link-ip.nextdns.io`, I didn't see this domain in my logs. I only add those domains that I see in my logs.

**Comment by correabuscar** [comment]
@teakoder makes sense, thank you for reporting.

There are a bunch of random-looking `*.test.nextdns.io` that I'm seeing in uMatrix with Firefox, when visiting `my.nextdns.io` too. Who knows what others. I doubt blocking any subdomain under `nextdns.io` was a good idea anyway, but maybe I'm wrong.

You can see `link-ip.nextdns.io` in the first tab called `Setup`, on the right under `Linked IP` where it says:
>If you are unable to set up NextDNS using our apps, DNS-over-TLS, DNS-over-HTTPS or IPv6, then use the DNS servers below and link your IP. This is mostly for use on home networks and not recommended on mobile.`

then expand the `Show advanced options` from below, where it says: `You can also programmatically update your linked IP by calling:`, there you can see that hostname `link-ip.nextdns.io` mentioned.

**Comment by correabuscar** [comment]
`*.io` is all blocked, this might not be Energized Ultimate's fault, maybe? more investigation is needed

**Comment by teakoder** [comment]
> There are a bunch of random-looking `*.test.nextdns.io` that I'm seeing in uMatrix with Firefox, when visiting `my.nextdns.io` too.

I see. I'm not using uMatrix. I'm seeing the blocked domains in NextDNS's "Logs". Thanks for the tips anyway. Would be useful in uBO.

> You can see `link-ip.nextdns.io` in the first tab called `Setup`, on the right under `Linked IP` where it says:

Right. I'm aware of that. My NextDNS setup is using DoH currently.

> **EDIT2**: unrelated, the [whitelist](https://raw.githubusercontent.com/AdroitAdorKhan/EnergizedProtection/master/core/filter/whitelist) is a lil bit suspicious, the last two entries, clearly not meant to be pointing at the real google:

I agree. The strings looks corrupted or the encoding is messed up. I'm not too sure.

> `*.io` is all blocked, this might not be Energized Ultimate's fault, maybe? more investigation is needed

Few hours earlier, upon carrying out a further investigation on my side, I noticed even more domains that were working previously but were blocked now. For examples:

```
blessed.rs
```

Since you brought up about the `*.io` is all blocked, now I'm thinking the blast radius is wider than I thought now.
I don't know and cannot conclude whether this might be Energized Ultimate's fault.

**Comment by teakoder** [comment]
Semi-related issue: #973
