### ISSUE TITLE
Major sites are blocked in the recent update

### ISSUE THREAD

**Issue by FR46M3N7-P4R71CL3** [EnergizedProtection/block#973]
<h1 align="center">Energized Protection - block ⚡</h1>
<div align="center">
  <strong>Let's make an annoyance free, better open internet, altogether!</strong>
</div>

<h2 align="center">Issue Submit Form</h2>
<div align="center">
  Provide the following info properly, which will help us to resolve your issue quickly.
</div>

### Issue(s):
Type `x` in between `[ ]` and make sure there isn't any space between brackets. Example; for Your Selected Issue(s), type like this - `[x]` 
You can select more than one category of issues if you need to!

- [x] Whitelist
- [ ] Blacklist
- [ ] App Broken
- [ ] Website Broken
- [ ] Request
- [ ] Other Issue

<hr>

### Pack(s):
Write the name of the pack(s) you are using.

- Pack(s) Name: 

<hr>

### Extension(s):
Also name the extension(s) if you are using any. If you don't then leave it blank.

- Extension(s) Name: 

<hr>

### Domain(s):
If you are submitting this issue for whitelist/blacklist issue, send us the domain(s) for whitelisting/blacklisting here. Kindly use the **Code Tag** to prevent tracking.

- Domain(s):

```
my.nextdns.io
www.amazon.in
msh.amazon.co.uk
downdetector.in
```

<hr>

### Your Config:
Just to ensure there is no issues or conflicts with other app/software/magisk module/extension/source list. 
Make sure you are running Energized Protection Service only.

- Client: NextDNS Blocking list

- Version: 

<hr>

### Detail:
Write us a lil bit more about your issue or query. You can attach any screen shot or log of the issue or advert, this will help to highlight it.

- Your Issue Detail: 
Some major sites seem to be blocked by the recently updated filters. I've been using the EnergizedProtection on NextDns.io

<hr>

<div align="center">
  <h2>Thank you for making Energized Protection great, with your kind help!</h2>
  <sub>A project by <a href="https://nayemador.com" target="_blank">Ador</a> with ❤<pub>
</div>

**Comment by botthebestplayerintheworld** [comment]
https://github.com/EnergizedProtection/block/issues/972
https://github.com/nextdns/metadata/issues/1145
https://help.nextdns.io/t/m1hs207/energized-ultimate-lists-blocking-nextdns
https://help.nextdns.io/t/q6hs204/nextdns-io-addresses-added-to-a-blocklist-internet-goes-down

**Comment by damienbutt** [comment]
nextdns.io
vodafone.co.uk
tailscale.io
plex.tv
snapcraft.io

All are being blocked. WTF?

**Comment by FR46M3N7-P4R71CL3** [comment]
PS: There's likely something broken with @NextDNS. Many filters have 0 entries or very few entries against them.
May be we should reach out to NextDNS support.

**Comment by botthebestplayerintheworld** [comment]
![Screenshot 2022-11-25 at 15-12-36 Privacy - bot - NextDNS](https://user-images.githubusercontent.com/96731476/203922561-d683bb06-ecbe-455e-8206-3156bfcebadc.png)
seems like recently updated lists are having problems

**Comment by mad-it** [comment]
Even banks are blocked right now...
ing.nl
knab.nl
abnamro.nl

**Comment by botthebestplayerintheworld** [comment]
.gg .io .me blocked

**Comment by SQLDBAWithABeard** [comment]
I have removed this list from my nextdns for now as the latest update has made all my users (my wife) very unhappy

**Comment by milindgoel15** [comment]
Even Spotify shareable shit is blocked

**Comment by ngalaiko** [comment]
bye bye from my list

**Comment by FR46M3N7-P4R71CL3** [comment]
> bye bye from my list

As I've mentioned, this doesn't seem to be the fault of the Energized list:

> PS: There's likely something broken with @nextdns. Many filters have 0 entries or very few entries against them. May be we should reach out to NextDNS support.

Good news everyone, the issue seems to have been resolved by NextDNS:
![image](https://user-images.githubusercontent.com/12612215/204029074-0e297088-c754-498b-8e46-17b8fa8ad6dd.png)

🥳🎉

To avoid the NextDNS dashboard being inaccessible in the future for a similar reason:
Try adding "nextdns.io" (without quotes) in the "Allowlist" explicitly. This will automatically whitelist the pages used by NextDNS.

If you're affected, all websites should now (hopefully) work without doing anything on our side.

**Comment by milindgoel15** [comment]
Hey, just wanted to know how this was caused by nextdns. I mean the logs on nextdns said these sites and apps are being blocked by energized. So what was the actual reason?

**Comment by FR46M3N7-P4R71CL3** [comment]
> ![Screenshot 2022-11-25 at 15-12-36 Privacy - bot - NextDNS](https://user-images.githubusercontent.com/96731476/203922561-d683bb06-ecbe-455e-8206-3156bfcebadc.png) seems like some recently updated lists are having problems.

I've checked the actual list of Energized Ultimate domains and compared it against the NextDNS's. As others have also pointed out, the entries for several lists don't match the official figures, which suggests that NextDNS must have had errors in fetching or during parsing of the entries at the server-side.

Link to energized ultimate hosts - https://energized.pro/ultimate/formats/hosts.txt

**Comment by FR46M3N7-P4R71CL3** [comment]
As to how NextDNS may have showed this was blocked by Energized is that during import, if something fails, it imports data till that point. Some line that contains .gg/.io must have been partially imported and this must have caused a block of all matching sites.

Regex-like match should be used at NextDNS side to quickly match the DNS queries against blocklist and this must have caused false positives, causing NextDNS to flag those as inadvertently blocked by Energized Ultimate List.

The lack of response from NextDNS concerns me though, the above is just my educated guess.

**Comment by rfxcll** [comment]
#916 
Just letting you know.

It's definitelly NextDNS backend that's causing all of us to come to this place though.

**Comment by FR46M3N7-P4R71CL3** [comment]
> #916 Just letting you know.
> 
> It's definitelly NextDNS backend that's causing all of us to come to this place though.

![image](https://user-images.githubusercontent.com/12612215/204034674-9d6cc086-4ff5-452b-b42c-2bc379b813a7.png)
The issue seems to have affected all Energized lists and a few non-energized lists as well, according to Reddit.

![image](https://user-images.githubusercontent.com/12612215/204036402-3077ade8-3d0d-48a1-9cd0-6536300eac13.png)

Unsure who's responsible for the blocks.

**Comment by botthebestplayerintheworld** [comment]
LOL
I have found the entries increased about 7 hours ago but I just went to sleep after that.

**Comment by rfxcll** [comment]
#980 
And now we are having problem with the energized regional version, looks like I'm going to remove yet another one from my blocklist.
Sorry, but waking up to another suprise was no more.

**Comment by adityasubathu** [comment]
It's not nextdns backend. It's energized auto updater or something. Regional extension is explicitly blocking google.com. I downloaded the list in hosts format from their website.

![Screenshot 2022-11-27 112623](https://user-images.githubusercontent.com/16309657/204121421-d8826268-bc90-4342-a29c-1fac82e3dcef.png)

**Comment by adityasubathu** [comment]
please re-open this issue

**Comment by damienbutt** [comment]
It started blocking netflix.com last night.

That was the last straw. Disabled. 

God knows what’s going on.

**Comment by FR46M3N7-P4R71CL3** [comment]
#916 #980 and others exist for similar issues, not reopening on a per-case basis.

**Comment by milindgoel15** [comment]
Now it blocks Twitter. 

Yep I'm leaving energized as well.

**Comment by Wizardling** [comment]
First time I've seen a blocklist selfdestruct like this. But any faith I once had in Energized is gone.
